import type { Question } from './types';

/**
 * Banco de preguntas. La opción correcta va SIEMPRE primera: el deck baraja
 * las opciones al armar cada ronda, así que acá se escribe cómodo.
 *
 * Para sumar preguntas: pegá objetos nuevos y listo. TypeScript se queja si
 * te falta una opción o la categoría no existe.
 */
export const QUESTIONS: Question[] = [
  // -- videojuegos ----------------------------------------------------------
  { id: 'vj01', category: 'videojuegos', difficulty: 1, text: '¿Qué compañía creó la saga The Legend of Zelda?', options: ['Nintendo', 'Sega', 'Sony', 'Capcom'] },
  { id: 'vj02', category: 'videojuegos', difficulty: 1, text: '¿Qué junta Sonic a lo largo de los niveles?', options: ['Anillos', 'Monedas', 'Estrellas', 'Gemas'] },
  { id: 'vj03', category: 'videojuegos', difficulty: 2, text: '¿En qué juego aparece la ciudad submarina de Rapture?', options: ['BioShock', 'Subnautica', 'Half-Life 2', 'Dishonored'] },
  { id: 'vj04', category: 'videojuegos', difficulty: 1, text: '¿Cuál es el videojuego más vendido de la historia?', options: ['Minecraft', 'Tetris', 'GTA V', 'Wii Sports'] },
  { id: 'vj05', category: 'videojuegos', difficulty: 2, text: '¿Qué estudio desarrolló Dark Souls?', options: ['FromSoftware', 'Bethesda', 'Team Ninja', 'Platinum Games'] },
  { id: 'vj06', category: 'videojuegos', difficulty: 2, text: '¿Cómo se llama la yegua de Link en Ocarina of Time?', options: ['Epona', 'Navi', 'Malon', 'Saria'] },
  { id: 'vj07', category: 'videojuegos', difficulty: 2, text: '¿Qué estudio desarrolló The Witcher 3?', options: ['CD Projekt Red', 'Ubisoft', 'BioWare', 'Bethesda'] },
  { id: 'vj08', category: 'videojuegos', difficulty: 2, text: '¿En qué año salió el primer Super Mario Bros.?', options: ['1985', '1981', '1990', '1978'] },
  { id: 'vj09', category: 'videojuegos', difficulty: 1, text: '¿De qué color es Blinky, el fantasma que persigue a Pac-Man?', options: ['Rojo', 'Rosa', 'Celeste', 'Naranja'] },
  { id: 'vj10', category: 'videojuegos', difficulty: 3, text: '¿Cuál es el arma icónica de Gordon Freeman en Half-Life?', options: ['La palanca', 'La escopeta', 'La ballesta', 'La llave inglesa'] },
  { id: 'vj11', category: 'videojuegos', difficulty: 1, text: '¿Cómo se llama el protagonista de la saga Metal Gear Solid?', options: ['Solid Snake', 'Sam Fisher', 'Big Boss', 'Raiden'], note: 'Big Boss es su padre genético, pero el prota del primero es Solid Snake.' },
  { id: 'vj12', category: 'videojuegos', difficulty: 2, text: '¿Cómo se llama el reino donde vive Mario?', options: ['Reino Champiñón', 'Reino Estrella', 'Reino Koopa', 'Reino Yoshi'] },
  { id: 'vj13', category: 'videojuegos', difficulty: 3, text: '¿Qué juego popularizó la frase "The cake is a lie"?', options: ['Portal', 'Half-Life', 'Left 4 Dead', 'Team Fortress 2'] },
  { id: 'vj14', category: 'videojuegos', difficulty: 2, text: '¿Cuántos personajes jugables tenía el Super Smash Bros. original de N64?', options: ['12', '8', '16', '20'] },

  { id: 'vj15', category: 'videojuegos', difficulty: 1, text: '¿Qué empresa fabricó la consola Dreamcast?', options: ['Sega', 'Nintendo', 'Sony', 'Atari'] },
  { id: 'vj16', category: 'videojuegos', difficulty: 2, text: 'En Portal, ¿cómo se llama la inteligencia artificial que te habla?', options: ['GLaDOS', 'SHODAN', 'Cortana', 'HAL 9000'] },
  { id: 'vj17', category: 'videojuegos', difficulty: 2, text: '¿A qué se dedicaba Gordon Freeman antes del desastre de Half-Life?', options: ['Físico teórico', 'Ingeniero militar', 'Médico', 'Guardia de seguridad'] },
  { id: 'vj18', category: 'videojuegos', difficulty: 1, text: '¿En qué saga aparece Kratos?', options: ['God of War', 'Devil May Cry', 'Bayonetta', 'Darksiders'] },
  { id: 'vj19', category: 'videojuegos', difficulty: 2, text: 'Además de comida, madera y oro, ¿qué recurso se junta en Age of Empires II?', options: ['Piedra', 'Hierro', 'Carbón', 'Petróleo'] },
  { id: 'vj20', category: 'videojuegos', difficulty: 1, text: '¿Cómo se llama el villano de la saga Sonic?', options: ['Doctor Eggman', 'Bowser', 'Ganondorf', 'Wario'] },
  { id: 'vj21', category: 'videojuegos', difficulty: 1, text: '¿Qué consola de Nintendo tenía dos pantallas?', options: ['Nintendo DS', 'Game Boy Advance', 'GameCube', 'Nintendo 64'] },
  { id: 'vj22', category: 'videojuegos', difficulty: 1, text: '¿En qué ciudad transcurre Grand Theft Auto V?', options: ['Los Santos', 'Vice City', 'Liberty City', 'San Fierro'] },
  { id: 'vj23', category: 'videojuegos', difficulty: 1, text: '¿Qué compañía desarrolló Overwatch?', options: ['Blizzard', 'Valve', 'Riot Games', 'Epic Games'] },
  { id: 'vj24', category: 'videojuegos', difficulty: 2, text: '¿Qué juego ganó el premio al Juego del Año en 2022?', options: ['Elden Ring', 'God of War Ragnarök', 'Horizon Forbidden West', 'Stray'] },
  { id: 'vj25', category: 'videojuegos', difficulty: 1, text: '¿Cómo se llama el protagonista de Uncharted?', options: ['Nathan Drake', 'Lara Croft', 'Sam Fisher', 'Ethan Mars'] },
  { id: 'vj26', category: 'videojuegos', difficulty: 2, text: '¿Qué animal es Crash Bandicoot?', options: ['Un bandicut', 'Un zorro', 'Un mapache', 'Una comadreja'] },
  { id: 'vj27', category: 'videojuegos', difficulty: 2, text: 'En Tetris, ¿qué letra tiene la pieza de cuatro cuadros en fila?', options: ['I', 'L', 'T', 'O'] },
  { id: 'vj28', category: 'videojuegos', difficulty: 1, text: "¿Qué compañía publica Assassin's Creed?", options: ['Ubisoft', 'EA', 'Activision', 'Rockstar'] },
  { id: 'vj29', category: 'videojuegos', difficulty: 3, text: 'Sony iba a fabricar su primera consola junto a otra empresa, hasta que se pelearon. ¿Cuál era?', options: ['Nintendo', 'Sega', 'Philips', 'Atari'] },
  { id: 'vj30', category: 'videojuegos', difficulty: 1, text: '¿En qué modo de Minecraft podés volar y tenés recursos infinitos?', options: ['Creativo', 'Supervivencia', 'Aventura', 'Extremo'] },
  { id: 'vj31', category: 'videojuegos', difficulty: 2, text: '¿De qué país es Blanka, de Street Fighter?', options: ['Brasil', 'Japón', 'Rusia', 'India'] },
  { id: 'vj32', category: 'videojuegos', difficulty: 1, text: '¿Cuántos jugadores tiene cada equipo en League of Legends?', options: ['5', '4', '6', '3'] },
  { id: 'vj33', category: 'videojuegos', difficulty: 2, text: '¿Cómo se llama la moneda del mundo de Zelda?', options: ['Rupias', 'Bayas', 'Anillos', 'Bells'] },
  { id: 'vj34', category: 'videojuegos', difficulty: 2, text: 'En Dark Souls, ¿qué sirve a la vez de moneda y de experiencia?', options: ['Las almas', 'Los ecos', 'Las runas', 'Los fragmentos'] },
  { id: 'vj35', category: 'videojuegos', difficulty: 2, text: '¿Qué juego arrancó como un mod de ARMA y popularizó el battle royale?', options: ['PUBG', 'Fortnite', 'Apex Legends', 'Warzone'] },
  { id: 'vj36', category: 'videojuegos', difficulty: 3, text: '¿Cuál fue la primera consola doméstica de la historia?', options: ['Magnavox Odyssey', 'Atari 2600', 'Nintendo NES', 'ColecoVision'] },

  // -- anime ----------------------------------------------------------------
  { id: 'an01', category: 'anime', difficulty: 1, text: '¿Cuántas esferas del dragón hay que juntar en Dragon Ball?', options: ['7', '5', '9', '10'] },
  { id: 'an02', category: 'anime', difficulty: 1, text: '¿Cuál es el sueño declarado de Naruto?', options: ['Ser Hokage', 'Vengar a su clan', 'Ser el más fuerte', 'Encontrar a su padre'] },
  { id: 'an03', category: 'anime', difficulty: 2, text: '¿Cómo se llama el shinigami que sigue a Light en Death Note?', options: ['Ryuk', 'Rem', 'Sidoh', 'Gelus'] },
  { id: 'an04', category: 'anime', difficulty: 2, text: '¿Qué buscan los hermanos Elric en Fullmetal Alchemist?', options: ['Recuperar sus cuerpos', 'Vengar a su madre', 'Derrotar al Führer', 'Encontrar a su padre'] },
  { id: 'an05', category: 'anime', difficulty: 1, text: '¿Qué estudio produjo El viaje de Chihiro?', options: ['Studio Ghibli', 'Madhouse', 'Toei Animation', 'Kyoto Animation'] },
  { id: 'an06', category: 'anime', difficulty: 2, text: '¿Quién es el autor de One Piece?', options: ['Eiichiro Oda', 'Masashi Kishimoto', 'Akira Toriyama', 'Tite Kubo'] },
  { id: 'an07', category: 'anime', difficulty: 2, text: '¿Cómo se llama el poder ocular del clan Uchiha?', options: ['Sharingan', 'Byakugan', 'Rinnegan', 'Tenseigan'] },
  { id: 'an08', category: 'anime', difficulty: 1, text: '¿De qué tipo es Pikachu?', options: ['Eléctrico', 'Normal', 'Fuego', 'Psíquico'] },
  { id: 'an09', category: 'anime', difficulty: 3, text: '¿Qué fruta del diablo comió Luffy en One Piece?', options: ['Gomu Gomu no Mi', 'Mera Mera no Mi', 'Hito Hito no Mi', 'Ope Ope no Mi'] },
  { id: 'an10', category: 'anime', difficulty: 2, text: '¿Cómo se llama el titán que hereda Eren en Attack on Titan?', options: ['Titán de Ataque', 'Titán Colosal', 'Titán Bestia', 'Titán Acorazado'] },
  { id: 'an11', category: 'anime', difficulty: 3, text: '¿Qué película dirigió Hayao Miyazaki sobre una chica criada por lobos?', options: ['La princesa Mononoke', 'Nausicaä', 'Ponyo', 'El castillo ambulante'] },
  { id: 'an12', category: 'anime', difficulty: 2, text: 'En Evangelion, ¿cómo se llama el robot que pilotea Shinji?', options: ['EVA Unidad 01', 'EVA Unidad 00', 'EVA Unidad 02', 'EVA Unidad 03'] },
  { id: 'an13', category: 'anime', difficulty: 3, text: 'En Cowboy Bebop, ¿cómo se llama la nave de Spike y Jet?', options: ['Bebop', 'Swordfish', 'Red Tail', 'Hammerhead'] },

  { id: 'an14', category: 'anime', difficulty: 1, text: '¿Cómo se llama el hermano mayor de los Elric?', options: ['Edward', 'Alphonse', 'Roy', 'Van Hohenheim'] },
  { id: 'an15', category: 'anime', difficulty: 2, text: '¿Cómo se llama el segundo barco de los Sombrero de Paja?', options: ['Thousand Sunny', 'Going Merry', 'Red Force', 'Moby Dick'] },
  { id: 'an16', category: 'anime', difficulty: 1, text: 'En Death Note, ¿cómo se hace llamar el detective que persigue a Kira?', options: ['L', 'Near', 'Mello', 'Watari'] },
  { id: 'an17', category: 'anime', difficulty: 1, text: '¿Cómo se llama la aldea donde vive Naruto?', options: ['Konoha', 'Suna', 'Kiri', 'Iwa'] },
  { id: 'an18', category: 'anime', difficulty: 1, text: 'En Demon Slayer, ¿cómo se llama la hermana de Tanjiro?', options: ['Nezuko', 'Kanao', 'Shinobu', 'Mitsuri'] },
  { id: 'an19', category: 'anime', difficulty: 2, text: "¿Quién creó JoJo's Bizarre Adventure?", options: ['Hirohiko Araki', 'Kentaro Miura', 'Tite Kubo', 'Yoshihiro Togashi'] },
  { id: 'an20', category: 'anime', difficulty: 2, text: 'En Sailor Moon, ¿cómo se llama la gata negra?', options: ['Luna', 'Artemis', 'Diana', 'Selene'] },
  { id: 'an21', category: 'anime', difficulty: 2, text: '¿Qué comen los guerreros de Dragon Ball para recuperarse por completo?', options: ['Semillas del ermitaño', 'Fruta del árbol divino', 'Agua ultra divina', 'Néctar de Kami'] },
  { id: 'an22', category: 'anime', difficulty: 2, text: 'En Hunter x Hunter, ¿cómo se llama la energía que aprenden a manejar?', options: ['Nen', 'Ki', 'Chakra', 'Reiatsu'] },
  { id: 'an23', category: 'anime', difficulty: 3, text: '¿Qué estudio animó Neon Genesis Evangelion?', options: ['Gainax', 'Bones', 'Sunrise', 'Madhouse'] },
  { id: 'an24', category: 'anime', difficulty: 2, text: '¿Cuántos Pokémon tenía la primera generación?', options: ['151', '150', '251', '100'] },
  { id: 'an25', category: 'anime', difficulty: 2, text: 'En My Hero Academia, ¿cómo se llama el poder que hereda Deku?', options: ['One For All', 'All For One', 'Plus Ultra', 'Detroit Smash'] },
  { id: 'an26', category: 'anime', difficulty: 2, text: '¿Cómo se llama el perro de Cowboy Bebop?', options: ['Ein', 'Edward', 'Jet', 'Spike'] },
  { id: 'an27', category: 'anime', difficulty: 2, text: '¿Cómo se llama la técnica de clones de sombra de Naruto?', options: ['Kage Bunshin', 'Rasengan', 'Chidori', 'Susanoo'] },
  { id: 'an28', category: 'anime', difficulty: 1, text: '¿De qué deporte trata Haikyuu?', options: ['Vóley', 'Básquet', 'Fútbol', 'Béisbol'] },
  { id: 'an29', category: 'anime', difficulty: 1, text: '¿Cómo se llama el ataque más famoso de Goku?', options: ['Kamehameha', 'Genkidama', 'Kaioken', 'Big Bang Attack'] },
  { id: 'an30', category: 'anime', difficulty: 2, text: '¿Quién dibujó Berserk?', options: ['Kentaro Miura', 'Naoki Urasawa', 'Takehiko Inoue', 'Junji Ito'] },
  { id: 'an31', category: 'anime', difficulty: 1, text: '¿Cuál es la ley fundamental de la alquimia en Fullmetal Alchemist?', options: ['El intercambio equivalente', 'La transmutación libre', 'El círculo perfecto', 'La ley del más fuerte'] },
  { id: 'an32', category: 'anime', difficulty: 1, text: '¿Qué anime protagoniza Saitama?', options: ['One Punch Man', 'Mob Psycho 100', 'Gintama', 'Bleach'] },
  { id: 'an33', category: 'anime', difficulty: 2, text: 'En Chainsaw Man, ¿cómo se llama el demonio motosierra que acompaña a Denji?', options: ['Pochita', 'Power', 'Makima', 'Aki'] },
  { id: 'an34', category: 'anime', difficulty: 2, text: '¿A qué público apunta el género "shonen"?', options: ['Chicos jóvenes', 'Chicas jóvenes', 'Adultos', 'Nenes muy chicos'] },
  { id: 'an35', category: 'anime', difficulty: 3, text: '¿En qué ciudad transcurre Akira?', options: ['Neo-Tokio', 'Tokio-3', 'Ciudad Central', 'Midgar'] },

  // -- fantasía y libros ----------------------------------------------------
  { id: 'fa01', category: 'fantasia', difficulty: 1, text: '¿Quién escribió El Señor de los Anillos?', options: ['J.R.R. Tolkien', 'C.S. Lewis', 'George R.R. Martin', 'Terry Pratchett'] },
  { id: 'fa02', category: 'fantasia', difficulty: 2, text: '¿Cómo se llama el dragón de El Hobbit?', options: ['Smaug', 'Glaurung', 'Ancalagon', 'Drogon'] },
  { id: 'fa03', category: 'fantasia', difficulty: 1, text: '¿Qué casa de Hogwarts tiene un tejón como símbolo?', options: ['Hufflepuff', 'Ravenclaw', 'Gryffindor', 'Slytherin'] },
  { id: 'fa04', category: 'fantasia', difficulty: 1, text: '¿Cuál es el lema de la casa Stark?', options: ['Se acerca el invierno', 'Oye mi rugido', 'Fuego y sangre', 'Nuestra es la furia'] },
  { id: 'fa05', category: 'fantasia', difficulty: 2, text: '¿Cómo se llama la espada de Aragorn, reforjada de Narsil?', options: ['Andúril', 'Glamdring', 'Orcrist', 'Dardo'] },
  { id: 'fa06', category: 'fantasia', difficulty: 2, text: '¿Quién escribió Las Crónicas de Narnia?', options: ['C.S. Lewis', 'J.R.R. Tolkien', 'Roald Dahl', 'Philip Pullman'] },
  { id: 'fa07', category: 'fantasia', difficulty: 3, text: 'En El nombre del viento, ¿cómo se llama el protagonista?', options: ['Kvothe', 'Bast', 'Denna', 'Ambrose'] },
  { id: 'fa08', category: 'fantasia', difficulty: 3, text: '¿Sobre qué se sostiene el Mundodisco de Terry Pratchett?', options: ['Cuatro elefantes sobre una tortuga', 'Una serpiente gigante', 'Un árbol infinito', 'Nada, flota'] },
  { id: 'fa09', category: 'fantasia', difficulty: 2, text: '¿Qué criatura tiene cuerpo de león y cabeza y alas de águila?', options: ['Grifo', 'Quimera', 'Basilisco', 'Mantícora'] },
  { id: 'fa10', category: 'fantasia', difficulty: 3, text: 'En Mistborn, ¿cómo se llama la magia que consume metales?', options: ['Alomancia', 'Feruquimia', 'Hemalurgia', 'Investidura'] },
  { id: 'fa11', category: 'fantasia', difficulty: 2, text: '¿Cuántos Anillos de Poder se forjaron para los Hombres?', options: ['9', '7', '3', '1'] },
  { id: 'fa12', category: 'fantasia', difficulty: 2, text: '¿Quién escribió Fundación y Yo, Robot?', options: ['Isaac Asimov', 'Arthur C. Clarke', 'Philip K. Dick', 'Ray Bradbury'] },
  { id: 'fa13', category: 'fantasia', difficulty: 3, text: 'En Dune, ¿cómo se llama la especia del planeta Arrakis?', options: ['Melange', 'Sardaukar', 'Shai-Hulud', 'Kwisatz'] },

  { id: 'fa14', category: 'fantasia', difficulty: 1, text: '¿Quién escribió El Principito?', options: ['Antoine de Saint-Exupéry', 'Julio Verne', 'Albert Camus', 'Michael Ende'] },
  { id: 'fa15', category: 'fantasia', difficulty: 2, text: '¿Cómo se llama el caballo de Gandalf?', options: ['Sombragrís', 'Brego', 'Asfaloth', 'Nariz de Fuego'] },
  { id: 'fa16', category: 'fantasia', difficulty: 2, text: '¿Cómo se llama el elfo doméstico que sirvió a los Malfoy?', options: ['Dobby', 'Kreacher', 'Winky', 'Hokey'] },
  { id: 'fa17', category: 'fantasia', difficulty: 2, text: '¿Quién escribió Frankenstein?', options: ['Mary Shelley', 'Bram Stoker', 'Edgar Allan Poe', 'Emily Brontë'] },
  { id: 'fa18', category: 'fantasia', difficulty: 1, text: '¿Qué animal aparece en el escudo de la casa Lannister?', options: ['Un león', 'Un lobo', 'Un dragón', 'Un ciervo'] },
  { id: 'fa19', category: 'fantasia', difficulty: 3, text: 'En El Nombre del Viento, ¿qué instrumento toca Kvothe?', options: ['El laúd', 'El arpa', 'La flauta', 'El violín'] },
  { id: 'fa20', category: 'fantasia', difficulty: 2, text: '¿Quién escribió Un Mundo Feliz?', options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'] },
  { id: 'fa21', category: 'fantasia', difficulty: 2, text: 'En 1984, ¿cómo se llama la figura que encabeza el Partido?', options: ['El Gran Hermano', "O'Brien", 'Emmanuel Goldstein', 'El Ministerio de la Verdad'] },
  { id: 'fa22', category: 'fantasia', difficulty: 1, text: '¿Cómo se llama el mago oscuro que persigue a Harry Potter?', options: ['Voldemort', 'Grindelwald', 'Snape', 'Quirrell'] },
  { id: 'fa23', category: 'fantasia', difficulty: 2, text: '¿Qué criatura de la mitología griega tiene serpientes en lugar de pelo?', options: ['Medusa', 'La Hidra', 'La Quimera', 'Una arpía'] },
  { id: 'fa24', category: 'fantasia', difficulty: 3, text: '¿Quién escribió El Retrato de Dorian Gray?', options: ['Oscar Wilde', 'Bram Stoker', 'Robert Louis Stevenson', 'Arthur Conan Doyle'] },
  { id: 'fa25', category: 'fantasia', difficulty: 2, text: 'En El Hobbit, ¿qué encuentra Bilbo en la cueva de Gollum?', options: ['El Anillo Único', 'Una espada élfica', 'Un mapa', 'Una llave'] },
  { id: 'fa26', category: 'fantasia', difficulty: 2, text: '¿Quién escribió Cien Años de Soledad?', options: ['Gabriel García Márquez', 'Julio Cortázar', 'Mario Vargas Llosa', 'Jorge Luis Borges'] },
  { id: 'fa27', category: 'fantasia', difficulty: 2, text: 'En Juego de Tronos, ¿cómo se llama la espada de Ned Stark?', options: ['Hielo', 'Garra', 'Aguja', 'Guardajuramentos'] },
  { id: 'fa28', category: 'fantasia', difficulty: 2, text: '¿Qué autor argentino escribió Ficciones?', options: ['Jorge Luis Borges', 'Julio Cortázar', 'Adolfo Bioy Casares', 'Ernesto Sabato'] },
  { id: 'fa29', category: 'fantasia', difficulty: 1, text: '¿Cuántos libros tiene la saga de Harry Potter?', options: ['7', '6', '8', '5'] },
  { id: 'fa30', category: 'fantasia', difficulty: 3, text: 'En Dune, ¿cómo se llaman los gusanos gigantes de Arrakis?', options: ['Shai-Hulud', 'Sardaukar', 'Bene Gesserit', 'Mentat'] },
  { id: 'fa31', category: 'fantasia', difficulty: 2, text: '¿Quién escribió El Alquimista?', options: ['Paulo Coelho', 'Isabel Allende', 'José Saramago', 'Herman Hesse'] },
  { id: 'fa32', category: 'fantasia', difficulty: 2, text: 'En El Señor de los Anillos, ¿qué es Mordor?', options: ['El reino de Sauron', 'Un bosque encantado', 'Una ciudad enana', 'Un mar interior'] },
  { id: 'fa33', category: 'fantasia', difficulty: 3, text: '¿Cómo se llama el detective belga creado por Agatha Christie?', options: ['Hércules Poirot', 'Sherlock Holmes', 'Philip Marlowe', 'Auguste Dupin'] },
  { id: 'fa34', category: 'fantasia', difficulty: 2, text: 'En la mitología nórdica, ¿qué criatura es Fenrir?', options: ['Un lobo gigante', 'Una serpiente marina', 'Un caballo de ocho patas', 'Un dragón'] },
  { id: 'fa35', category: 'fantasia', difficulty: 1, text: '¿Quién escribió Drácula?', options: ['Bram Stoker', 'Mary Shelley', 'Edgar Allan Poe', 'H.P. Lovecraft'] },

  // -- programación ---------------------------------------------------------
  { id: 'pr01', category: 'programacion', difficulty: 1, text: '¿Qué significa la sigla HTML?', options: ['HyperText Markup Language', 'HighText Machine Language', 'Hyperlink Text Mode Language', 'Home Tool Markup Language'] },
  { id: 'pr02', category: 'programacion', difficulty: 1, text: '¿Quién creó el kernel de Linux?', options: ['Linus Torvalds', 'Richard Stallman', 'Ken Thompson', 'Dennis Ritchie'] },
  { id: 'pr03', category: 'programacion', difficulty: 2, text: '¿Qué estructura de datos funciona como LIFO?', options: ['Pila', 'Cola', 'Lista enlazada', 'Árbol'] },
  { id: 'pr04', category: 'programacion', difficulty: 2, text: '¿Cuál es la complejidad de una búsqueda binaria?', options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(1)'] },
  { id: 'pr05', category: 'programacion', difficulty: 2, text: '¿Qué lenguaje usa la extensión .rs?', options: ['Rust', 'Ruby', 'R', 'Racket'] },
  { id: 'pr06', category: 'programacion', difficulty: 1, text: '¿Qué significa el error HTTP 404?', options: ['No encontrado', 'Prohibido', 'Error del servidor', 'No autorizado'] },
  { id: 'pr07', category: 'programacion', difficulty: 2, text: '¿Cuánto da 0.1 + 0.2 en JavaScript?', options: ['0.30000000000000004', '0.3', '0.30000000001', 'NaN'] },
  { id: 'pr08', category: 'programacion', difficulty: 2, text: '¿Qué puerto usa HTTPS por defecto?', options: ['443', '80', '8080', '22'] },
  { id: 'pr09', category: 'programacion', difficulty: 2, text: '¿Quién es considerada la primera programadora de la historia?', options: ['Ada Lovelace', 'Grace Hopper', 'Margaret Hamilton', 'Hedy Lamarr'] },
  { id: 'pr10', category: 'programacion', difficulty: 1, text: '¿Qué lenguaje creó Guido van Rossum?', options: ['Python', 'Ruby', 'Perl', 'PHP'] },
  { id: 'pr11', category: 'programacion', difficulty: 3, text: '¿En cuántos días se creó la primera versión de JavaScript?', options: ['10', '30', '90', '3'] },
  { id: 'pr12', category: 'programacion', difficulty: 3, text: '¿Qué significa la sigla ACID en bases de datos?', options: ['Atomicidad, Consistencia, Aislamiento, Durabilidad', 'Acceso, Control, Índice, Datos', 'Asíncrono, Concurrente, Idempotente, Distribuido', 'Auditoría, Cifrado, Integridad, Disponibilidad'] },
  { id: 'pr13', category: 'programacion', difficulty: 2, text: '¿Qué comando de git descarga cambios del remoto sin fusionarlos?', options: ['git fetch', 'git pull', 'git clone', 'git merge'] },
  { id: 'pr14', category: 'programacion', difficulty: 3, text: '¿Cuál es el valor máximo de un entero con signo de 32 bits?', options: ['2147483647', '4294967295', '65535', '2147483648'] },

  { id: 'pr15', category: 'programacion', difficulty: 1, text: '¿Qué significa la sigla CSS?', options: ['Cascading Style Sheets', 'Computer Style System', 'Creative Style Sheets', 'Coded Syntax Standard'] },
  { id: 'pr16', category: 'programacion', difficulty: 2, text: '¿Qué estructura de datos funciona como FIFO?', options: ['Cola', 'Pila', 'Árbol', 'Grafo'] },
  { id: 'pr17', category: 'programacion', difficulty: 2, text: '¿Cuántos bits tiene un byte?', options: ['8', '4', '16', '32'] },
  { id: 'pr18', category: 'programacion', difficulty: 2, text: '¿En qué base numérica trabaja internamente una computadora?', options: ['Binaria', 'Decimal', 'Hexadecimal', 'Octal'] },
  { id: 'pr19', category: 'programacion', difficulty: 1, text: '¿Qué comando de git guarda los cambios en el historial local?', options: ['git commit', 'git save', 'git push', 'git stash'] },
  { id: 'pr20', category: 'programacion', difficulty: 2, text: '¿Qué significa la sigla API?', options: ['Interfaz de Programación de Aplicaciones', 'Aplicación Programada Interna', 'Acceso Público a Internet', 'Análisis de Procesos Informáticos'] },
  { id: 'pr21', category: 'programacion', difficulty: 2, text: '¿Qué empresa creó el lenguaje Go?', options: ['Google', 'Microsoft', 'Apple', 'Mozilla'] },
  { id: 'pr22', category: 'programacion', difficulty: 3, text: '¿Qué devuelve `typeof null` en JavaScript?', options: ['"object"', '"null"', '"undefined"', '"number"'], note: 'Es un bug histórico que nunca se pudo arreglar sin romper la web.' },
  { id: 'pr23', category: 'programacion', difficulty: 2, text: '¿Qué protocolo se usa para enviar correos electrónicos?', options: ['SMTP', 'HTTP', 'FTP', 'SSH'] },
  { id: 'pr24', category: 'programacion', difficulty: 3, text: '¿Cuántos colores distintos puede representar un pixel RGB de 24 bits?', options: ['Más de 16 millones', '65.536', '256', '4.096'] },
  { id: 'pr25', category: 'programacion', difficulty: 2, text: '¿Qué empresa desarrolló TypeScript?', options: ['Microsoft', 'Google', 'Meta', 'Oracle'] },
  { id: 'pr26', category: 'programacion', difficulty: 2, text: '¿Qué significa la sigla IDE?', options: ['Entorno de Desarrollo Integrado', 'Interfaz de Datos Externa', 'Índice de Desarrollo Estándar', 'Instalador de Entorno'] },
  { id: 'pr27', category: 'programacion', difficulty: 3, text: '¿Qué algoritmo de ordenamiento tiene peor caso O(n²) pero suele ser el más rápido en la práctica?', options: ['Quicksort', 'Mergesort', 'Heapsort', 'Bubblesort'] },
  { id: 'pr28', category: 'programacion', difficulty: 2, text: '¿Qué significa la sigla CPU?', options: ['Unidad Central de Procesamiento', 'Unidad de Cálculo Paralelo', 'Computadora de Propósito Único', 'Control de Programas y Utilidades'] },
  { id: 'pr29', category: 'programacion', difficulty: 1, text: '¿Con qué símbolo se abre un comentario de una línea en JavaScript?', options: ['//', '#', '--', '%%'] },
  { id: 'pr30', category: 'programacion', difficulty: 2, text: '¿Cuál de estas es una base de datos orientada a documentos?', options: ['MongoDB', 'PostgreSQL', 'MySQL', 'SQLite'] },
  { id: 'pr31', category: 'programacion', difficulty: 3, text: '¿En qué año se publicó la primera versión de Git?', options: ['2005', '2001', '2008', '1998'] },
  { id: 'pr32', category: 'programacion', difficulty: 2, text: '¿Qué hace el comando `rm -rf /` en Linux?', options: ['Borra todo el sistema de archivos', 'Reinicia la máquina', 'Repara permisos', 'Lista archivos ocultos'] },
  { id: 'pr33', category: 'programacion', difficulty: 2, text: '¿Qué quiere decir que un software sea "open source"?', options: ['Que su código fuente es público', 'Que es gratis', 'Que no tiene licencia', 'Que corre en cualquier sistema'] },
  { id: 'pr34', category: 'programacion', difficulty: 3, text: '¿Cómo se llama el error de una recursión que nunca termina?', options: ['Stack overflow', 'Memory leak', 'Null pointer', 'Race condition'] },
  { id: 'pr35', category: 'programacion', difficulty: 2, text: '¿Qué lenguaje usa la extensión .go?', options: ['Go', 'Groovy', 'Gosu', 'Godot Script'] },

  // -- cine -----------------------------------------------------------------
  { id: 'ci01', category: 'cine', difficulty: 1, text: '¿Quién dirigió Pulp Fiction?', options: ['Quentin Tarantino', 'Martin Scorsese', 'David Fincher', 'Guy Ritchie'] },
  { id: 'ci02', category: 'cine', difficulty: 1, text: 'En Matrix, ¿qué pastilla elige Neo?', options: ['La roja', 'La azul', 'Ninguna', 'Las dos'] },
  { id: 'ci03', category: 'cine', difficulty: 2, text: '¿Cómo se llama la pelota que acompaña a Tom Hanks en Náufrago?', options: ['Wilson', 'Spalding', 'Chuck', 'Vóley'] },
  { id: 'ci04', category: 'cine', difficulty: 2, text: '¿Quién dirigió Interstellar?', options: ['Christopher Nolan', 'Denis Villeneuve', 'Ridley Scott', 'Alfonso Cuarón'] },
  { id: 'ci05', category: 'cine', difficulty: 2, text: '¿Qué película coreana ganó el Óscar a Mejor Película?', options: ['Parásitos', 'Old Boy', 'Decision to Leave', 'Burning'] },
  { id: 'ci06', category: 'cine', difficulty: 2, text: '¿Cómo se llama el hotel de El Resplandor?', options: ['Overlook', 'Bates', 'Continental', 'Grand Budapest'] },
  { id: 'ci07', category: 'cine', difficulty: 1, text: '¿Quién dirigió El Padrino?', options: ['Francis Ford Coppola', 'Martin Scorsese', 'Sidney Lumet', 'Brian De Palma'] },
  { id: 'ci08', category: 'cine', difficulty: 2, text: '¿En qué película de Star Wars se revela "Yo soy tu padre"?', options: ['El Imperio Contraataca', 'Una Nueva Esperanza', 'El Retorno del Jedi', 'La Venganza de los Sith'] },
  { id: 'ci09', category: 'cine', difficulty: 2, text: '¿Qué película argentina ganó el Óscar a Mejor Película Extranjera en 2010?', options: ['El secreto de sus ojos', 'Relatos salvajes', 'La historia oficial', 'Nueve reinas'] },
  { id: 'ci10', category: 'cine', difficulty: 1, text: '¿Quién dirigió Jurassic Park?', options: ['Steven Spielberg', 'James Cameron', 'Robert Zemeckis', 'George Lucas'] },
  { id: 'ci11', category: 'cine', difficulty: 3, text: 'En El Club de la Pelea, ¿cuál es la primera regla?', options: ['No se habla del club', 'Solo dos por pelea', 'Sin camisas ni zapatos', 'La pelea termina cuando alguien se rinde'] },
  { id: 'ci12', category: 'cine', difficulty: 3, text: '¿Qué actor interpretó al Joker en El Caballero de la Noche?', options: ['Heath Ledger', 'Joaquin Phoenix', 'Jared Leto', 'Jack Nicholson'] },
  { id: 'ci13', category: 'cine', difficulty: 2, text: '¿De qué estudio es la película Toy Story?', options: ['Pixar', 'DreamWorks', 'Disney Animation', 'Blue Sky'] },

  { id: 'ci14', category: 'cine', difficulty: 1, text: '¿Quién dirigió Titanic?', options: ['James Cameron', 'Steven Spielberg', 'Ridley Scott', 'Michael Bay'] },
  { id: 'ci15', category: 'cine', difficulty: 2, text: '¿En qué película aparece Hannibal Lecter por primera vez con Anthony Hopkins?', options: ['El Silencio de los Inocentes', 'Hannibal', 'Dragón Rojo', 'Seven'] },
  { id: 'ci16', category: 'cine', difficulty: 2, text: '¿Cómo se llama el robot protagonista de la película de Pixar de 2008?', options: ['WALL·E', 'EVE', 'Baymax', 'Chappie'] },
  { id: 'ci17', category: 'cine', difficulty: 1, text: '¿En qué saga se dice "Que la Fuerza te acompañe"?', options: ['Star Wars', 'Star Trek', 'Dune', 'Battlestar Galactica'] },
  { id: 'ci18', category: 'cine', difficulty: 2, text: '¿Quién dirigió El Laberinto del Fauno?', options: ['Guillermo del Toro', 'Alejandro González Iñárritu', 'Alfonso Cuarón', 'Pedro Almodóvar'] },
  { id: 'ci19', category: 'cine', difficulty: 2, text: '¿Qué actor interpretó a Forrest Gump?', options: ['Tom Hanks', 'Kevin Costner', 'Robin Williams', 'Bill Murray'] },
  { id: 'ci20', category: 'cine', difficulty: 3, text: '¿Cuántos Óscar ganó El Señor de los Anillos: El Retorno del Rey?', options: ['11', '7', '9', '5'] },
  { id: 'ci21', category: 'cine', difficulty: 2, text: '¿Quién dirigió El Origen (Inception)?', options: ['Christopher Nolan', 'Denis Villeneuve', 'David Fincher', 'Darren Aronofsky'] },
  { id: 'ci22', category: 'cine', difficulty: 2, text: 'En El Padrino, ¿cuál es el apellido de la familia protagonista?', options: ['Corleone', 'Soprano', 'Gambino', 'Barzini'] },
  { id: 'ci23', category: 'cine', difficulty: 2, text: '¿Quién compuso la banda sonora de Star Wars?', options: ['John Williams', 'Hans Zimmer', 'Ennio Morricone', 'Danny Elfman'] },
  { id: 'ci24', category: 'cine', difficulty: 1, text: '¿Cómo se llama el personaje de Johnny Depp en Piratas del Caribe?', options: ['Jack Sparrow', 'Will Turner', 'Davy Jones', 'Barbossa'] },
  { id: 'ci25', category: 'cine', difficulty: 2, text: '¿Quién dirigió Mad Max: Furia en el Camino?', options: ['George Miller', 'Zack Snyder', 'Michael Bay', 'Neill Blomkamp'] },
  { id: 'ci26', category: 'cine', difficulty: 3, text: '¿Qué película argentina ganó el Óscar a Mejor Película Extranjera en 1986?', options: ['La historia oficial', 'Camila', 'El exilio de Gardel', 'Hombre mirando al sudeste'] },
  { id: 'ci27', category: 'cine', difficulty: 3, text: '¿Qué actor rechazó el Óscar que ganó por El Padrino?', options: ['Marlon Brando', 'Al Pacino', 'Robert De Niro', 'James Caan'] },
  { id: 'ci28', category: 'cine', difficulty: 1, text: '¿Qué animal es Simba en El Rey León?', options: ['Un león', 'Un tigre', 'Un leopardo', 'Una pantera'] },
  { id: 'ci29', category: 'cine', difficulty: 2, text: '¿Quién dirigió Kill Bill?', options: ['Quentin Tarantino', 'Robert Rodriguez', 'John Woo', 'Guy Ritchie'] },
  { id: 'ci30', category: 'cine', difficulty: 2, text: '¿Cómo se llama el planeta natal de Superman?', options: ['Krypton', 'Asgard', 'Tamaran', 'Oa'] },
  { id: 'ci31', category: 'cine', difficulty: 3, text: '¿En qué año se estrenó la primera película de Star Wars?', options: ['1977', '1980', '1972', '1983'] },
  { id: 'ci32', category: 'cine', difficulty: 2, text: '¿Qué película sobre un tren dirigió Bong Joon-ho antes de Parásitos?', options: ['Snowpiercer', 'Okja', 'Madre', 'The Host'] },
  { id: 'ci33', category: 'cine', difficulty: 2, text: '¿Qué película de animación japonesa ganó el Óscar en 2003?', options: ['El viaje de Chihiro', 'La princesa Mononoke', 'El castillo ambulante', 'Ponyo'] },
  { id: 'ci34', category: 'cine', difficulty: 2, text: '¿Qué estudio produce las películas de los Vengadores?', options: ['Marvel Studios', 'DC Films', 'Pixar', 'Lucasfilm'] },
  { id: 'ci35', category: 'cine', difficulty: 3, text: '¿Cuál es la película más taquillera de todos los tiempos sin ajustar por inflación?', options: ['Avatar', 'Avengers: Endgame', 'Titanic', 'Star Wars: El Despertar de la Fuerza'] },

  // -- series ---------------------------------------------------------------
  { id: 'se01', category: 'series', difficulty: 1, text: '¿En qué serie aparece Walter White?', options: ['Breaking Bad', 'Better Call Saul', 'Ozark', 'Narcos'] },
  { id: 'se02', category: 'series', difficulty: 1, text: '¿Cómo se llama el pueblo de Stranger Things?', options: ['Hawkins', 'Derry', 'Riverdale', 'Springfield'] },
  { id: 'se03', category: 'series', difficulty: 2, text: '¿Cómo se llama la empresa de papel de The Office?', options: ['Dunder Mifflin', 'Wernham Hogg', 'Vandelay', 'Sabre'] },
  { id: 'se04', category: 'series', difficulty: 1, text: '¿En qué ciudad transcurre Friends?', options: ['Nueva York', 'Chicago', 'Boston', 'Los Ángeles'] },
  { id: 'se05', category: 'series', difficulty: 2, text: '¿A qué se dedica Dexter Morgan durante el día?', options: ['Analista de salpicaduras de sangre', 'Detective', 'Forense de autopsias', 'Fotógrafo policial'] },
  { id: 'se06', category: 'series', difficulty: 2, text: '¿Cuántas temporadas tuvo Breaking Bad?', options: ['5', '4', '6', '7'] },
  { id: 'se07', category: 'series', difficulty: 2, text: '¿Cómo se llama el bar de How I Met Your Mother?', options: ["MacLaren's", "Paddy's", 'Central Perk', "Moe's"] },
  { id: 'se08', category: 'series', difficulty: 2, text: 'En Rick y Morty, ¿cómo se llama la hermana de Morty?', options: ['Summer', 'Beth', 'Jessica', 'Tammy'] },
  { id: 'se09', category: 'series', difficulty: 1, text: '¿Qué serie animada transcurre en Springfield?', options: ['Los Simpson', 'Padre de Familia', 'South Park', 'Bob Esponja'] },
  { id: 'se10', category: 'series', difficulty: 2, text: '¿Qué serie protagoniza Pedro Pascal como Joel?', options: ['The Last of Us', 'The Mandalorian', 'Narcos', 'Game of Thrones'] },
  { id: 'se11', category: 'series', difficulty: 3, text: 'En Los Soprano, ¿cómo se llama el psiquiatra de Tony?', options: ['Dra. Melfi', 'Dr. Kupferberg', 'Dra. Krakower', 'Dr. Cusamano'] },
  { id: 'se12', category: 'series', difficulty: 3, text: 'En Lost, ¿qué números aparecen una y otra vez?', options: ['4 8 15 16 23 42', '3 7 11 13 17 19', '1 2 3 5 8 13', '6 12 18 24 30 36'] },
  { id: 'se13', category: 'series', difficulty: 2, text: '¿Qué serie tiene como lema "Winter is coming"?', options: ['Game of Thrones', 'Vikings', 'The Witcher', 'The Last Kingdom'] },

  { id: 'se14', category: 'series', difficulty: 1, text: '¿En qué serie aparece el doctor Gregory House?', options: ['House M.D.', "Grey's Anatomy", 'ER', 'Scrubs'] },
  { id: 'se15', category: 'series', difficulty: 2, text: '¿Cómo se llama la serie derivada (precuela) de Breaking Bad?', options: ['Better Call Saul', 'El Camino', 'Ozark', 'Bloodline'] },
  { id: 'se16', category: 'series', difficulty: 2, text: 'En Game of Thrones, ¿quién mata al Rey de la Noche?', options: ['Arya Stark', 'Jon Snow', 'Bran Stark', 'Daenerys'] },
  { id: 'se17', category: 'series', difficulty: 1, text: '¿Qué serie sigue a un grupo de científicos y su vecina aspirante a actriz?', options: ['The Big Bang Theory', 'Friends', 'How I Met Your Mother', 'Community'] },
  { id: 'se18', category: 'series', difficulty: 2, text: 'En la serie Chernobyl, ¿qué número de reactor explota?', options: ['El 4', 'El 1', 'El 2', 'El 3'] },
  { id: 'se19', category: 'series', difficulty: 2, text: '¿Qué serie de Netflix sigue a la familia real británica?', options: ['The Crown', 'Downton Abbey', 'Victoria', 'Bridgerton'] },
  { id: 'se20', category: 'series', difficulty: 2, text: '¿En qué serie animada aparece el robot Bender?', options: ['Futurama', 'Los Simpson', 'Padre de Familia', 'Rick y Morty'] },
  { id: 'se21', category: 'series', difficulty: 3, text: '¿Cómo se llama la startup protagonista de Silicon Valley?', options: ['Pied Piper', 'Hooli', 'Aviato', 'Raviga'] },
  { id: 'se22', category: 'series', difficulty: 2, text: '¿Qué serie coreana de Netflix trata sobre juegos infantiles mortales?', options: ['El Juego del Calamar', 'Sweet Home', 'Kingdom', 'All of Us Are Dead'] },
  { id: 'se23', category: 'series', difficulty: 2, text: 'En The Mandalorian, ¿cuál es el verdadero nombre de "Baby Yoda"?', options: ['Grogu', 'Din Djarin', 'Kuiil', 'Cara Dune'] },
  { id: 'se24', category: 'series', difficulty: 3, text: '¿Cuántos episodios tiene la miniserie Chernobyl?', options: ['5', '6', '8', '10'] },
  { id: 'se25', category: 'series', difficulty: 2, text: '¿En qué década transcurre principalmente Mad Men?', options: ['Los 60', 'Los 50', 'Los 70', 'Los 80'] },
  { id: 'se26', category: 'series', difficulty: 2, text: '¿Cómo se llama el protagonista de The Witcher?', options: ['Geralt de Rivia', 'Jaskier', 'Vesemir', 'Lambert'] },
  { id: 'se27', category: 'series', difficulty: 2, text: 'Además de Los Simpson, ¿qué serie animada creó Matt Groening?', options: ['Futurama', 'South Park', 'Padre de Familia', 'Rick y Morty'] },
  { id: 'se28', category: 'series', difficulty: 2, text: 'En Peaky Blinders, ¿cómo se apellida la familia protagonista?', options: ['Shelby', 'Solomons', 'Changretta', 'Gray'] },
  { id: 'se29', category: 'series', difficulty: 2, text: '¿Qué serie de HBO transcurre en un parque temático lleno de androides?', options: ['Westworld', 'Black Mirror', 'Devs', 'Raised by Wolves'] },
  { id: 'se30', category: 'series', difficulty: 1, text: '¿Cómo se llama el bar de Los Simpson?', options: ['La taberna de Moe', 'El Chanchito Feliz', 'Krusty Burger', 'La bolera de Barney'] },
  { id: 'se31', category: 'series', difficulty: 2, text: 'En Stranger Things, ¿cuál es el poder principal de Once?', options: ['Telequinesis', 'Invisibilidad', 'Viajar en el tiempo', 'Leer el futuro'] },
  { id: 'se32', category: 'series', difficulty: 1, text: '¿En qué serie trabaja el abogado Harvey Specter?', options: ['Suits', 'The Good Wife', 'Billions', 'Damages'] },
  { id: 'se33', category: 'series', difficulty: 2, text: 'En Breaking Bad, ¿cómo se llama el cuñado de Walter que trabaja en la DEA?', options: ['Hank', 'Gus', 'Mike', 'Saul'] },
  { id: 'se34', category: 'series', difficulty: 3, text: '¿Qué programa tiene el récord de más premios Emmy ganados?', options: ['Saturday Night Live', 'Los Simpson', 'Game of Thrones', 'Friends'] },
  { id: 'se35', category: 'series', difficulty: 2, text: '¿Qué serie de Netflix sigue a una prodigio del ajedrez?', options: ['Gambito de Dama', 'The Crown', 'Ozark', 'Mindhunter'] },

  // -- comida ---------------------------------------------------------------
  { id: 'co01', category: 'comida', difficulty: 1, text: '¿De qué país es originaria la pizza?', options: ['Italia', 'Grecia', 'Estados Unidos', 'Turquía'] },
  { id: 'co02', category: 'comida', difficulty: 1, text: '¿Cuál es el ingrediente principal del guacamole?', options: ['Palta', 'Pepino', 'Zapallo', 'Poroto'] },
  { id: 'co03', category: 'comida', difficulty: 2, text: '¿De qué está hecho el hummus?', options: ['Garbanzos', 'Lentejas', 'Porotos blancos', 'Arvejas'] },
  { id: 'co04', category: 'comida', difficulty: 2, text: '¿Qué es el umami?', options: ['El quinto sabor básico', 'Un corte de atún', 'Una técnica de cocción', 'Un tipo de alga'] },
  { id: 'co05', category: 'comida', difficulty: 2, text: '¿Qué pasta tiene forma de moñito?', options: ['Farfalle', 'Fusilli', 'Penne', 'Rigatoni'] },
  { id: 'co06', category: 'comida', difficulty: 1, text: '¿De qué país es originario el kimchi?', options: ['Corea del Sur', 'Japón', 'China', 'Vietnam'] },
  { id: 'co07', category: 'comida', difficulty: 2, text: '¿Qué queso lleva la pizza napolitana tradicional?', options: ['Mozzarella', 'Provolone', 'Parmesano', 'Gorgonzola'] },
  { id: 'co08', category: 'comida', difficulty: 3, text: '¿Qué es un roux en cocina?', options: ['Harina y manteca cocidas', 'Un caldo reducido', 'Una emulsión de huevo', 'Un fondo de verduras'] },
  { id: 'co09', category: 'comida', difficulty: 2, text: '¿Cuál es el ingrediente base del sushi, además del pescado?', options: ['Arroz', 'Fideos', 'Alga nori', 'Soja'] },
  { id: 'co10', category: 'comida', difficulty: 2, text: '¿Qué parte del ají concentra más picante?', options: ['Las venas y semillas', 'La piel', 'La punta', 'El tallo'] },
  { id: 'co11', category: 'comida', difficulty: 1, text: '¿Con qué se toma tradicionalmente el mate?', options: ['Bombilla', 'Sorbete', 'Cuchara', 'Pajita de vidrio'] },
  { id: 'co12', category: 'comida', difficulty: 3, text: '¿Qué temperatura marca el punto de caramelo en el azúcar?', options: ['170 °C', '100 °C', '120 °C', '250 °C'] },
  { id: 'co13', category: 'comida', difficulty: 2, text: '¿Qué le da el color rojo al pimentón?', options: ['El pimiento seco molido', 'El tomate deshidratado', 'La remolacha', 'El ají picante'] },

  { id: 'co14', category: 'comida', difficulty: 1, text: '¿De qué país es originario el sushi tal como lo conocemos?', options: ['Japón', 'China', 'Corea', 'Tailandia'] },
  { id: 'co15', category: 'comida', difficulty: 2, text: 'Además de albahaca, ¿qué fruto seco lleva el pesto genovés?', options: ['Piñones', 'Nueces pecán', 'Almendras', 'Castañas'] },
  { id: 'co16', category: 'comida', difficulty: 2, text: '¿Cuál es el ingrediente principal de la polenta?', options: ['Maíz', 'Trigo', 'Arroz', 'Papa'] },
  { id: 'co17', category: 'comida', difficulty: 2, text: '¿De qué está hecho el tofu?', options: ['Soja', 'Arroz', 'Garbanzo', 'Almendra'] },
  { id: 'co18', category: 'comida', difficulty: 3, text: '¿Qué significa "mise en place" en una cocina?', options: ['Tener todo preparado antes de cocinar', 'Una técnica de corte', 'Un tipo de salsa madre', 'Un horno de leña'] },
  { id: 'co19', category: 'comida', difficulty: 2, text: '¿De qué animal es la leche de la mozzarella original italiana?', options: ['Búfala', 'Vaca', 'Cabra', 'Oveja'] },
  { id: 'co20', category: 'comida', difficulty: 1, text: '¿A qué temperatura hierve el agua a nivel del mar?', options: ['100 °C', '90 °C', '120 °C', '80 °C'] },
  { id: 'co21', category: 'comida', difficulty: 3, text: '¿Qué compuesto le da el picor al jengibre?', options: ['El gingerol', 'La capsaicina', 'La piperina', 'La alicina'] },
  { id: 'co22', category: 'comida', difficulty: 2, text: 'Además de la remolacha, ¿de qué planta se extrae el azúcar?', options: ['La caña de azúcar', 'El maíz', 'La palma', 'El agave'] },
  { id: 'co23', category: 'comida', difficulty: 3, text: '¿Qué es un consomé?', options: ['Un caldo clarificado', 'Una salsa espesa', 'Un pan sin levadura', 'Un postre helado'] },
  { id: 'co24', category: 'comida', difficulty: 1, text: '¿Qué fruta tiene las semillas por fuera?', options: ['La frutilla', 'La uva', 'La manzana', 'El durazno'] },
  { id: 'co25', category: 'comida', difficulty: 2, text: '¿De qué país es originaria la paella?', options: ['España', 'Italia', 'Portugal', 'Grecia'] },
  { id: 'co26', category: 'comida', difficulty: 2, text: '¿Qué queso lleva el tiramisú?', options: ['Mascarpone', 'Ricota', 'Cottage', 'Provolone'] },
  { id: 'co27', category: 'comida', difficulty: 2, text: '¿De qué planta se destila el tequila?', options: ['El agave', 'La caña de azúcar', 'La papa', 'El maíz'] },
  { id: 'co28', category: 'comida', difficulty: 2, text: '¿Qué quiere decir que una pasta esté "al dente"?', options: ['Que queda firme al morder', 'Que se cocina al horno', 'Que lleva mucho queso', 'Que se sirve fría'] },
  { id: 'co29', category: 'comida', difficulty: 2, text: '¿Cuál es la base del ceviche?', options: ['Pescado crudo marinado en limón', 'Camarón cocido al vapor', 'Pulpo a la parrilla', 'Arroz con mariscos'] },
  { id: 'co30', category: 'comida', difficulty: 1, text: '¿Qué fruto seco es la base del turrón tradicional?', options: ['La almendra', 'La nuez', 'La avellana', 'La castaña'] },
  { id: 'co31', category: 'comida', difficulty: 3, text: '¿Cuál de estas NO es una de las salsas madre de la cocina francesa?', options: ['La mayonesa', 'La bechamel', 'La velouté', 'La holandesa'] },
  { id: 'co32', category: 'comida', difficulty: 2, text: '¿Qué corte de carne se usa para el clásico asado de tira?', options: ['La costilla', 'El lomo', 'El cuadril', 'La bola de lomo'] },
  { id: 'co33', category: 'comida', difficulty: 2, text: '¿Qué le da el color y el sabor al azafrán?', options: ['Los estigmas de una flor', 'La raíz de una planta', 'Una semilla molida', 'La corteza de un árbol'] },
  { id: 'co34', category: 'comida', difficulty: 1, text: '¿Cuál es el ingrediente principal del pan?', options: ['La harina', 'El azúcar', 'El huevo', 'La leche'] },
  { id: 'co35', category: 'comida', difficulty: 3, text: '¿Qué reacción química dora la carne y el pan al cocinarse?', options: ['La reacción de Maillard', 'La fermentación', 'La emulsión', 'La caramelización del agua'] },

  // -- cultura general ------------------------------------------------------
  { id: 'cu01', category: 'cultura', difficulty: 1, text: '¿Cuál es el planeta más grande del sistema solar?', options: ['Júpiter', 'Saturno', 'Neptuno', 'Urano'] },
  { id: 'cu02', category: 'cultura', difficulty: 2, text: '¿Cuántos huesos tiene un cuerpo humano adulto?', options: ['206', '186', '226', '256'] },
  { id: 'cu03', category: 'cultura', difficulty: 1, text: '¿Cuál es el océano más grande del mundo?', options: ['Pacífico', 'Atlántico', 'Índico', 'Ártico'] },
  { id: 'cu04', category: 'cultura', difficulty: 1, text: '¿En qué año pisó el hombre la Luna por primera vez?', options: ['1969', '1961', '1972', '1957'] },
  { id: 'cu05', category: 'cultura', difficulty: 2, text: '¿Qué elemento tiene el símbolo químico Au?', options: ['Oro', 'Plata', 'Aluminio', 'Cobre'] },
  { id: 'cu06', category: 'cultura', difficulty: 2, text: '¿Cuál es la capital de Australia?', options: ['Canberra', 'Sídney', 'Melbourne', 'Perth'] },
  { id: 'cu07', category: 'cultura', difficulty: 1, text: '¿Cuál es el animal terrestre más rápido?', options: ['Guepardo', 'León', 'Antílope', 'Caballo'] },
  { id: 'cu08', category: 'cultura', difficulty: 1, text: '¿Quién pintó La Gioconda?', options: ['Leonardo da Vinci', 'Miguel Ángel', 'Rafael', 'Botticelli'] },
  { id: 'cu09', category: 'cultura', difficulty: 1, text: '¿Cuál es el país más extenso del mundo?', options: ['Rusia', 'Canadá', 'China', 'Estados Unidos'] },
  { id: 'cu10', category: 'cultura', difficulty: 2, text: '¿Qué gas absorben las plantas para hacer fotosíntesis?', options: ['Dióxido de carbono', 'Oxígeno', 'Nitrógeno', 'Hidrógeno'] },
  { id: 'cu11', category: 'cultura', difficulty: 3, text: '¿Cuántos corazones tiene un pulpo?', options: ['3', '1', '2', '5'] },
  { id: 'cu12', category: 'cultura', difficulty: 2, text: '¿Cuál es el hueso más largo del cuerpo humano?', options: ['Fémur', 'Tibia', 'Húmero', 'Peroné'] },
  { id: 'cu13', category: 'cultura', difficulty: 3, text: '¿Qué país tiene más husos horarios?', options: ['Francia', 'Rusia', 'Estados Unidos', 'China'], note: 'Francia gana por sus territorios de ultramar: 12.' },
  { id: 'cu14', category: 'cultura', difficulty: 1, text: '¿Cuál es el desierto cálido más grande del mundo?', options: ['El Sahara', 'El Gobi', 'El Kalahari', 'El Atacama'] },
  { id: 'cu15', category: 'cultura', difficulty: 1, text: '¿En qué país están las pirámides de Giza?', options: ['Egipto', 'México', 'Perú', 'Sudán'] },
  { id: 'cu16', category: 'cultura', difficulty: 2, text: '¿Qué metal es líquido a temperatura ambiente?', options: ['El mercurio', 'El plomo', 'El estaño', 'El cobre'] },
  { id: 'cu17', category: 'cultura', difficulty: 2, text: '¿Cuántos lados tiene un dodecágono?', options: ['12', '10', '20', '14'] },
  { id: 'cu18', category: 'cultura', difficulty: 2, text: '¿Cuál es el idioma con más hablantes nativos del mundo?', options: ['El chino mandarín', 'El inglés', 'El español', 'El hindi'] },
  { id: 'cu19', category: 'cultura', difficulty: 1, text: '¿Qué planeta es conocido como el planeta rojo?', options: ['Marte', 'Venus', 'Júpiter', 'Mercurio'] },
  { id: 'cu20', category: 'cultura', difficulty: 2, text: '¿Quién formuló la teoría de la relatividad?', options: ['Albert Einstein', 'Isaac Newton', 'Niels Bohr', 'Max Planck'] },
  { id: 'cu21', category: 'cultura', difficulty: 2, text: '¿Cuál es el animal terrestre más grande?', options: ['El elefante africano', 'La jirafa', 'El rinoceronte', 'El hipopótamo'] },
  { id: 'cu22', category: 'cultura', difficulty: 2, text: '¿En qué año cayó el Muro de Berlín?', options: ['1989', '1991', '1985', '1975'] },
  { id: 'cu23', category: 'cultura', difficulty: 1, text: '¿Cuántos minutos dura un partido de fútbol reglamentario?', options: ['90', '80', '100', '120'] },
  { id: 'cu24', category: 'cultura', difficulty: 2, text: '¿Cuál es el río más largo de Sudamérica?', options: ['El Amazonas', 'El Paraná', 'El Orinoco', 'El Magdalena'] },
  { id: 'cu25', category: 'cultura', difficulty: 2, text: '¿Qué instrumento mide la presión atmosférica?', options: ['El barómetro', 'El termómetro', 'El higrómetro', 'El anemómetro'] },
  { id: 'cu26', category: 'cultura', difficulty: 3, text: '¿Cuántos huesos tiene una mano humana?', options: ['27', '19', '32', '24'] },
  { id: 'cu27', category: 'cultura', difficulty: 2, text: '¿Qué país tiene forma de bota?', options: ['Italia', 'Grecia', 'Chile', 'Noruega'] },
  { id: 'cu28', category: 'cultura', difficulty: 1, text: '¿Cuál es la montaña más alta del mundo sobre el nivel del mar?', options: ['El Everest', 'El K2', 'El Aconcagua', 'El Kilimanjaro'] },
  { id: 'cu29', category: 'cultura', difficulty: 3, text: '¿Cuánto tarda la luz del Sol en llegar a la Tierra?', options: ['Unos 8 minutos', 'Un segundo', 'Una hora', 'Un día'] },
  { id: 'cu30', category: 'cultura', difficulty: 2, text: '¿Qué órgano produce la insulina?', options: ['El páncreas', 'El hígado', 'El riñón', 'El bazo'] },
  { id: 'cu31', category: 'cultura', difficulty: 3, text: '¿En qué territorio, hoy parte de Tanzania, nació Freddie Mercury?', options: ['Zanzíbar', 'Bombay', 'Ciudad del Cabo', 'Adén'] },
  { id: 'cu32', category: 'cultura', difficulty: 2, text: '¿Qué mamífero pone huevos?', options: ['El ornitorrinco', 'El armadillo', 'El erizo', 'El pangolín'] },
  { id: 'cu33', category: 'cultura', difficulty: 2, text: '¿Cuántas cuerdas tiene un violín?', options: ['4', '6', '5', '3'] },
  { id: 'cu34', category: 'cultura', difficulty: 3, text: '¿Cuál es el elemento más abundante del universo?', options: ['El hidrógeno', 'El oxígeno', 'El helio', 'El carbono'] },
  { id: 'cu35', category: 'cultura', difficulty: 2, text: '¿Cuántos colores tiene el arcoíris según la clasificación clásica?', options: ['7', '5', '6', '9'] },

  // -- deportes -------------------------------------------------------------
  { id: 'de01', category: 'deportes', difficulty: 1, text: '¿Cada cuántos años se juega el Mundial de fútbol?', options: ['4', '2', '3', '5'] },
  { id: 'de02', category: 'deportes', difficulty: 2, text: '¿En qué país se jugó el Mundial de 1978?', options: ['Argentina', 'Brasil', 'España', 'México'] },
  { id: 'de03', category: 'deportes', difficulty: 1, text: '¿Cuántos jugadores tiene un equipo de básquet en cancha?', options: ['5', '6', '7', '4'] },
  { id: 'de04', category: 'deportes', difficulty: 1, text: '¿Qué selección ganó el Mundial de Qatar 2022?', options: ['Argentina', 'Francia', 'Brasil', 'Croacia'] },
  { id: 'de05', category: 'deportes', difficulty: 2, text: '¿Cuántos sets hay que ganar en un partido masculino de Grand Slam?', options: ['3', '2', '4', '5'] },
  { id: 'de06', category: 'deportes', difficulty: 1, text: '¿En qué deporte existe el "home run"?', options: ['Béisbol', 'Cricket', 'Fútbol americano', 'Hockey'] },
  { id: 'de07', category: 'deportes', difficulty: 1, text: '¿Cuántos anillos tiene el símbolo olímpico?', options: ['5', '4', '6', '3'] },
  { id: 'de08', category: 'deportes', difficulty: 2, text: '¿Cuánto mide una maratón?', options: ['42 km', '50 km', '21 km', '35 km'] },
  { id: 'de09', category: 'deportes', difficulty: 2, text: '¿En qué ciudad fueron los Juegos Olímpicos de 2016?', options: ['Río de Janeiro', 'Londres', 'Tokio', 'Pekín'] },
  { id: 'de10', category: 'deportes', difficulty: 2, text: '¿Qué selección ganó más Mundiales de fútbol?', options: ['Brasil', 'Alemania', 'Italia', 'Argentina'] },
  { id: 'de11', category: 'deportes', difficulty: 1, text: '¿En qué deporte se destacó Michael Jordan?', options: ['Básquet', 'Béisbol', 'Fútbol americano', 'Golf'] },
  { id: 'de12', category: 'deportes', difficulty: 2, text: '¿Cuántos jugadores tiene un equipo de vóley en cancha?', options: ['6', '5', '7', '4'] },
  { id: 'de13', category: 'deportes', difficulty: 2, text: '¿En qué país nació el judo?', options: ['Japón', 'China', 'Corea', 'Tailandia'] },
  { id: 'de14', category: 'deportes', difficulty: 2, text: '¿Cuál de los cuatro Grand Slam de tenis se juega sobre césped?', options: ['Wimbledon', 'Roland Garros', 'US Open', 'Australian Open'] },
  { id: 'de15', category: 'deportes', difficulty: 1, text: '¿Cuántos hoyos tiene un campo de golf reglamentario?', options: ['18', '9', '20', '24'] },
  { id: 'de16', category: 'deportes', difficulty: 2, text: '¿En qué deporte se compite por la Copa Stanley?', options: ['Hockey sobre hielo', 'Básquet', 'Béisbol', 'Fútbol americano'] },
  { id: 'de17', category: 'deportes', difficulty: 2, text: '¿Quién tiene el récord de más Balones de Oro?', options: ['Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff'] },
  { id: 'de18', category: 'deportes', difficulty: 2, text: '¿De qué país es el club de fútbol Ajax?', options: ['Países Bajos', 'Bélgica', 'Alemania', 'Dinamarca'] },
  { id: 'de19', category: 'deportes', difficulty: 2, text: '¿Cuánto dura un cuarto en la NBA?', options: ['12 minutos', '10 minutos', '15 minutos', '20 minutos'] },
  { id: 'de20', category: 'deportes', difficulty: 2, text: '¿Cuál de estos NO es un torneo de Grand Slam de tenis?', options: ['La Copa Davis', 'Wimbledon', 'Roland Garros', 'El US Open'] },
  { id: 'de21', category: 'deportes', difficulty: 2, text: '¿Qué nadador ganó más medallas olímpicas de la historia?', options: ['Michael Phelps', 'Mark Spitz', 'Ian Thorpe', 'Caeleb Dressel'] },
  { id: 'de22', category: 'deportes', difficulty: 3, text: '¿En qué país nació el rugby?', options: ['Inglaterra', 'Gales', 'Nueva Zelanda', 'Sudáfrica'] },
  { id: 'de23', category: 'deportes', difficulty: 3, text: '¿Cuál es la escudería más antigua que sigue en la Fórmula 1?', options: ['Ferrari', 'McLaren', 'Williams', 'Red Bull'] },
  { id: 'de24', category: 'deportes', difficulty: 1, text: '¿Qué significa "KO" en boxeo?', options: ['Knock out', 'Knock over', 'Keep out', 'King out'] },
  { id: 'de25', category: 'deportes', difficulty: 2, text: '¿En cuántos tiempos se divide un partido de rugby?', options: ['2', '3', '4', '1'] },
  { id: 'de26', category: 'deportes', difficulty: 2, text: '¿Qué selección ganó la Copa América 2021?', options: ['Argentina', 'Brasil', 'Uruguay', 'Colombia'] },
  { id: 'de27', category: 'deportes', difficulty: 2, text: '¿En qué deporte compite Simone Biles?', options: ['Gimnasia artística', 'Atletismo', 'Natación', 'Clavados'] },
  { id: 'de28', category: 'deportes', difficulty: 3, text: '¿Cuál es el estadio de fútbol más grande de Argentina?', options: ['El Monumental', 'La Bombonera', 'El Único de La Plata', 'El Cilindro'] },
  { id: 'de29', category: 'deportes', difficulty: 2, text: '¿Qué se lleva el líder del Tour de France?', options: ['El maillot amarillo', 'El maillot verde', 'Una copa dorada', 'Un cinturón'] },
  { id: 'de30', category: 'deportes', difficulty: 3, text: '¿Cuántos jugadores tiene un equipo de handball en cancha?', options: ['7', '6', '5', '8'] },
  { id: 'de31', category: 'deportes', difficulty: 1, text: '¿En qué juego existe el jaque mate?', options: ['El ajedrez', 'Las damas', 'El Go', 'El backgammon'] },
  { id: 'de32', category: 'deportes', difficulty: 2, text: '¿Qué país organizó el Mundial de fútbol de 2018?', options: ['Rusia', 'Brasil', 'Sudáfrica', 'Alemania'] },
  { id: 'de33', category: 'deportes', difficulty: 3, text: '¿Cómo se llama la jugada de ajedrez donde el rey y la torre se mueven juntos?', options: ['El enroque', 'El jaque', 'La promoción', 'La captura al paso'] },
  { id: 'de34', category: 'deportes', difficulty: 2, text: '¿En qué deporte se compite sobre un tatami?', options: ['Judo', 'Esgrima', 'Boxeo', 'Halterofilia'] },
  { id: 'de35', category: 'deportes', difficulty: 3, text: '¿Cuántos minutos dura un tiempo de un partido de básquet FIBA?', options: ['10', '12', '15', '20'] },

  // -- música ---------------------------------------------------------------
  { id: 'mu01', category: 'musica', difficulty: 1, text: '¿De qué país eran los Beatles?', options: ['Inglaterra', 'Estados Unidos', 'Irlanda', 'Australia'] },
  { id: 'mu02', category: 'musica', difficulty: 1, text: '¿Cuántas cuerdas tiene una guitarra clásica?', options: ['6', '4', '5', '7'] },
  { id: 'mu03', category: 'musica', difficulty: 2, text: '¿Quién compuso la Novena Sinfonía?', options: ['Beethoven', 'Mozart', 'Bach', 'Brahms'] },
  { id: 'mu04', category: 'musica', difficulty: 1, text: '¿Qué banda grabó "Bohemian Rhapsody"?', options: ['Queen', 'The Rolling Stones', 'Led Zeppelin', 'Pink Floyd'] },
  { id: 'mu05', category: 'musica', difficulty: 3, text: '¿Qué banda formó Charly García junto a Nito Mestre?', options: ['Sui Generis', 'Serú Girán', 'Los Abuelos de la Nada', 'Almendra'] },
  { id: 'mu06', category: 'musica', difficulty: 2, text: '¿Cuántas teclas tiene un piano estándar?', options: ['88', '76', '61', '96'] },
  { id: 'mu07', category: 'musica', difficulty: 2, text: '¿Qué género musical nació en Jamaica?', options: ['El reggae', 'La salsa', 'El tango', 'La cumbia'] },
  { id: 'mu08', category: 'musica', difficulty: 3, text: '¿Quién grabó el álbum "Alta Suciedad"?', options: ['Andrés Calamaro', 'Fito Páez', 'Charly García', 'Luis Alberto Spinetta'] },
  { id: 'mu09', category: 'musica', difficulty: 3, text: '¿Qué banda tocó en la azotea de Apple Records en 1969?', options: ['The Beatles', 'The Rolling Stones', 'The Who', 'Pink Floyd'] },
  { id: 'mu10', category: 'musica', difficulty: 2, text: '¿Cuál es el álbum más vendido de la historia?', options: ['Thriller', 'The Dark Side of the Moon', 'Back in Black', 'Rumours'] },
  { id: 'mu11', category: 'musica', difficulty: 1, text: '¿Qué instrumento tocaba Jimi Hendrix?', options: ['La guitarra', 'El bajo', 'La batería', 'El saxofón'] },
  { id: 'mu12', category: 'musica', difficulty: 3, text: '¿Quién compuso "Adiós Nonino"?', options: ['Astor Piazzolla', 'Carlos Gardel', 'Aníbal Troilo', 'Osvaldo Pugliese'] },
  { id: 'mu13', category: 'musica', difficulty: 2, text: '¿Cuántos músicos tiene un cuarteto de cuerdas?', options: ['4', '3', '5', '6'] },
  { id: 'mu14', category: 'musica', difficulty: 2, text: '¿Qué banda grabó "The Dark Side of the Moon"?', options: ['Pink Floyd', 'Led Zeppelin', 'The Doors', 'Genesis'] },
  { id: 'mu15', category: 'musica', difficulty: 1, text: '¿A qué cantante le dicen "el Rey del Pop"?', options: ['Michael Jackson', 'Elvis Presley', 'Prince', 'Freddie Mercury'] },
  { id: 'mu16', category: 'musica', difficulty: 2, text: 'En la escala musical, ¿qué nota sigue después de "si"?', options: ['Do', 'La', 'Re', 'Sol'] },
  { id: 'mu17', category: 'musica', difficulty: 3, text: '¿Quién escribió "Muchacha (Ojos de Papel)"?', options: ['Luis Alberto Spinetta', 'Charly García', 'Fito Páez', 'Gustavo Cerati'] },
  { id: 'mu18', category: 'musica', difficulty: 1, text: '¿Qué banda lideró Gustavo Cerati?', options: ['Soda Stereo', 'Virus', 'Sumo', 'Los Twist'] },
  { id: 'mu19', category: 'musica', difficulty: 2, text: '¿Cuántas líneas tiene un pentagrama?', options: ['5', '4', '6', '3'] },
  { id: 'mu20', category: 'musica', difficulty: 3, text: '¿Qué instrumento inventó Adolphe Sax?', options: ['El saxofón', 'El clarinete', 'La trompeta', 'El oboe'] },
  { id: 'mu21', category: 'musica', difficulty: 2, text: '¿Qué banda grabó "Stairway to Heaven"?', options: ['Led Zeppelin', 'Deep Purple', 'Black Sabbath', 'The Who'] },
  { id: 'mu22', category: 'musica', difficulty: 1, text: '¿De qué país es originario el K-pop?', options: ['Corea del Sur', 'Japón', 'China', 'Tailandia'] },
  { id: 'mu23', category: 'musica', difficulty: 2, text: '¿Qué cantante lanzó el álbum "1989"?', options: ['Taylor Swift', 'Adele', 'Lorde', 'Katy Perry'] },
  { id: 'mu24', category: 'musica', difficulty: 2, text: '¿Qué instrumento tiene martillos que golpean cuerdas?', options: ['El piano', 'El arpa', 'La guitarra', 'El violín'] },
  { id: 'mu25', category: 'musica', difficulty: 2, text: '¿Cómo se llamó el festival de 1969 en el estado de Nueva York?', options: ['Woodstock', 'Glastonbury', 'Monterey', 'Isle of Wight'] },
  { id: 'mu26', category: 'musica', difficulty: 3, text: '¿Quién compuso la música de El Padrino?', options: ['Nino Rota', 'Ennio Morricone', 'John Williams', 'Henry Mancini'] },
  { id: 'mu27', category: 'musica', difficulty: 2, text: '¿Qué banda lideró el Indio Solari?', options: ['Patricio Rey y sus Redonditos de Ricota', 'Sumo', 'Divididos', 'Las Pelotas'] },
  { id: 'mu28', category: 'musica', difficulty: 3, text: '¿Cuántos movimientos tiene habitualmente una sinfonía clásica?', options: ['4', '3', '5', '2'] },
  { id: 'mu29', category: 'musica', difficulty: 1, text: '¿Qué banda grabó "Smells Like Teen Spirit"?', options: ['Nirvana', 'Pearl Jam', 'Soundgarden', 'Alice in Chains'] },
  { id: 'mu30', category: 'musica', difficulty: 1, text: '¿Cuál de estos instrumentos se toca con arco?', options: ['El violín', 'La flauta', 'La trompeta', 'El acordeón'] },
  { id: 'mu31', category: 'musica', difficulty: 3, text: '¿Qué artista ganó más premios Grammy en la historia?', options: ['Beyoncé', 'Quincy Jones', 'Stevie Wonder', 'U2'] },
  { id: 'mu32', category: 'musica', difficulty: 2, text: '¿Qué quiere decir cantar "a capela"?', options: ['Sin acompañamiento instrumental', 'En coro', 'Muy agudo', 'Improvisando la letra'] },
  { id: 'mu33', category: 'musica', difficulty: 1, text: '¿De qué banda era Freddie Mercury?', options: ['Queen', 'The Kinks', 'The Clash', 'Oasis'] },
  { id: 'mu34', category: 'musica', difficulty: 2, text: '¿En qué ciudad estadounidense nació el jazz?', options: ['Nueva Orleans', 'Chicago', 'Nueva York', 'Detroit'] },
  { id: 'mu35', category: 'musica', difficulty: 3, text: '¿Cuál fue el segundo álbum de estudio de Soda Stereo?', options: ['Nada Personal', 'Signos', 'Canción Animal', 'Doble Vida'] },

  // -- historia -------------------------------------------------------------
  { id: 'hi01', category: 'historia', difficulty: 1, text: '¿En qué año empezó la Segunda Guerra Mundial?', options: ['1939', '1914', '1941', '1945'] },
  { id: 'hi02', category: 'historia', difficulty: 2, text: '¿Quién fue el primer emperador romano?', options: ['Augusto', 'Julio César', 'Nerón', 'Trajano'] },
  { id: 'hi03', category: 'historia', difficulty: 1, text: '¿En qué año se declaró la independencia argentina?', options: ['1816', '1810', '1820', '1853'] },
  { id: 'hi04', category: 'historia', difficulty: 1, text: '¿Qué civilización construyó Machu Picchu?', options: ['Los incas', 'Los mayas', 'Los aztecas', 'Los olmecas'] },
  { id: 'hi05', category: 'historia', difficulty: 3, text: '¿En qué año cayó el Imperio Romano de Occidente?', options: ['476', '1453', '395', '800'] },
  { id: 'hi06', category: 'historia', difficulty: 2, text: '¿Quién lideró la Revolución Rusa de 1917?', options: ['Lenin', 'Stalin', 'Trotsky', 'Kerensky'] },
  { id: 'hi07', category: 'historia', difficulty: 3, text: '¿Cuánto duró en realidad la Guerra de los Cien Años?', options: ['116 años', '100 años', '80 años', '150 años'] },
  { id: 'hi08', category: 'historia', difficulty: 1, text: '¿Qué muro cayó en 1989?', options: ['El Muro de Berlín', 'La Muralla China', 'El Muro de Adriano', 'El Muro de las Lamentaciones'] },
  { id: 'hi09', category: 'historia', difficulty: 1, text: '¿Quién fue el primer presidente de Estados Unidos?', options: ['George Washington', 'Thomas Jefferson', 'John Adams', 'Abraham Lincoln'] },
  { id: 'hi10', category: 'historia', difficulty: 1, text: '¿En qué año llegó Colón a América?', options: ['1492', '1500', '1453', '1519'] },
  { id: 'hi11', category: 'historia', difficulty: 2, text: '¿Qué faraón fue hallado casi intacto en 1922?', options: ['Tutankamón', 'Ramsés II', 'Keops', 'Akenatón'] },
  { id: 'hi12', category: 'historia', difficulty: 2, text: '¿Qué imperio conquistó Hernán Cortés?', options: ['El azteca', 'El inca', 'El maya', 'El chibcha'] },
  { id: 'hi13', category: 'historia', difficulty: 2, text: '¿En qué año terminó la Primera Guerra Mundial?', options: ['1918', '1919', '1917', '1920'] },
  { id: 'hi14', category: 'historia', difficulty: 2, text: '¿Quién escribió el Manifiesto Comunista junto a Engels?', options: ['Karl Marx', 'Lenin', 'Bakunin', 'Proudhon'] },
  { id: 'hi15', category: 'historia', difficulty: 2, text: '¿Qué país mandó al primer humano al espacio?', options: ['La Unión Soviética', 'Estados Unidos', 'China', 'Alemania'] },
  { id: 'hi16', category: 'historia', difficulty: 3, text: '¿Cómo se llamaba el barco en el que viajó Darwin?', options: ['Beagle', 'Endeavour', 'Victoria', 'Santa María'] },
  { id: 'hi17', category: 'historia', difficulty: 1, text: '¿Qué revolución empezó en 1789?', options: ['La Revolución Francesa', 'La Revolución Industrial', 'La Revolución Rusa', 'La independencia de EE.UU.'] },
  { id: 'hi18', category: 'historia', difficulty: 2, text: '¿Quién lideró la independencia de la India?', options: ['Gandhi', 'Nehru', 'Bose', 'Jinnah'] },
  { id: 'hi19', category: 'historia', difficulty: 2, text: '¿En qué provincia se declaró la independencia argentina?', options: ['Tucumán', 'Buenos Aires', 'Córdoba', 'Salta'] },
  { id: 'hi20', category: 'historia', difficulty: 3, text: '¿Qué dinastía china levantó la Gran Muralla tal como se ve hoy?', options: ['La Ming', 'La Han', 'La Qin', 'La Tang'] },
  { id: 'hi21', category: 'historia', difficulty: 3, text: '¿En qué año cayó Constantinopla en manos otomanas?', options: ['1453', '1492', '1204', '1071'] },
  { id: 'hi22', category: 'historia', difficulty: 2, text: '¿Quién pintó el techo de la Capilla Sixtina?', options: ['Miguel Ángel', 'Leonardo da Vinci', 'Rafael', 'Botticelli'] },
  { id: 'hi23', category: 'historia', difficulty: 1, text: '¿Quién fue el primer hombre en pisar la Luna?', options: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'] },
  { id: 'hi24', category: 'historia', difficulty: 1, text: '¿Qué guerra enfrentó a Argentina y el Reino Unido en 1982?', options: ['Malvinas', 'Del Chaco', 'De la Triple Alianza', 'Del Pacífico'] },
  { id: 'hi25', category: 'historia', difficulty: 3, text: '¿Qué documento firmó el rey Juan de Inglaterra en 1215?', options: ['La Carta Magna', 'La Declaración de Derechos', 'El Acta de Unión', 'El Tratado de Windsor'] },
  { id: 'hi26', category: 'historia', difficulty: 1, text: '¿Qué invento de Gutenberg cambió la historia?', options: ['La imprenta de tipos móviles', 'El papel', 'La tinta', 'El telescopio'] },
  { id: 'hi27', category: 'historia', difficulty: 2, text: '¿Qué ciudad sepultó la erupción del Vesubio en el año 79?', options: ['Pompeya', 'Atenas', 'Cartago', 'Éfeso'] },
  { id: 'hi28', category: 'historia', difficulty: 2, text: '¿En qué año se fundó la ONU?', options: ['1945', '1919', '1950', '1939'] },
  { id: 'hi29', category: 'historia', difficulty: 3, text: '¿Quién unificó Alemania en 1871?', options: ['Otto von Bismarck', 'Guillermo II', 'Federico el Grande', 'Konrad Adenauer'] },
  { id: 'hi30', category: 'historia', difficulty: 2, text: '¿Qué pueblo navegante llegó a América antes que Colón?', options: ['Los vikingos', 'Los fenicios', 'Los polinesios', 'Los chinos'] },
  { id: 'hi31', category: 'historia', difficulty: 2, text: '¿Qué presidente argentino gobernó entre 1946 y 1955?', options: ['Juan Domingo Perón', 'Hipólito Yrigoyen', 'Arturo Frondizi', 'Marcelo T. de Alvear'] },
  { id: 'hi32', category: 'historia', difficulty: 3, text: '¿Cómo se llamó el plan para reconstruir Europa tras la Segunda Guerra?', options: ['El Plan Marshall', 'El Plan Schuman', 'El Plan Dawes', 'El Plan Morgenthau'] },
  { id: 'hi33', category: 'historia', difficulty: 2, text: '¿Con qué animales cruzó Aníbal los Alpes?', options: ['Elefantes', 'Camellos', 'Bueyes', 'Mulas de guerra'] },
  { id: 'hi34', category: 'historia', difficulty: 2, text: '¿Qué imperio dominó el Mediterráneo antes de Roma y fue destruido por ella?', options: ['Cartago', 'Egipto', 'Macedonia', 'Persia'] },
  { id: 'hi35', category: 'historia', difficulty: 3, text: '¿En qué año se firmó la Declaración de Independencia de Estados Unidos?', options: ['1776', '1789', '1783', '1765'] },

  // -- internet -------------------------------------------------------------
  { id: 'in01', category: 'internet', difficulty: 1, text: '¿Qué significa "LOL"?', options: ['Laughing Out Loud', 'Lots Of Love', 'Lord Of Laughs', 'Live On Line'] },
  { id: 'in02', category: 'internet', difficulty: 1, text: '¿Cómo se llama hoy la red social que era Twitter?', options: ['X', 'Threads', 'Bluesky', 'Mastodon'] },
  { id: 'in03', category: 'internet', difficulty: 3, text: '¿Cuál fue el primer video subido a YouTube?', options: ['Me at the zoo', 'Charlie bit my finger', 'Evolution of Dance', 'Numa Numa'] },
  { id: 'in04', category: 'internet', difficulty: 1, text: '¿Qué animal era el logo original de Twitter?', options: ['Un pájaro', 'Un gato', 'Un zorro', 'Un búho'] },
  { id: 'in05', category: 'internet', difficulty: 3, text: 'Richard Dawkins acuñó la palabra "meme" para referirse a ____', options: ['Una unidad cultural que se replica', 'Una broma de internet', 'Un video corto', 'Una imagen con texto'] },
  { id: 'in06', category: 'internet', difficulty: 2, text: '¿De qué juego salió la frase "It\'s dangerous to go alone"?', options: ['The Legend of Zelda', 'Super Mario Bros.', 'Metroid', 'Final Fantasy'] },
  { id: 'in07', category: 'internet', difficulty: 2, text: '¿Cómo se llamaba el gato meme con cara de enojado permanente?', options: ['Grumpy Cat', 'Nyan Cat', 'Lil Bub', 'Keyboard Cat'] },
  { id: 'in08', category: 'internet', difficulty: 3, text: '¿Qué significa la sigla GIF?', options: ['Graphics Interchange Format', 'General Image File', 'Graphic Internet Frame', 'Global Image Format'] },
  { id: 'in09', category: 'internet', difficulty: 1, text: '¿Qué plataforma volvió masivos los videos verticales cortos?', options: ['TikTok', 'Instagram', 'YouTube', 'Snapchat'] },
  { id: 'in10', category: 'internet', difficulty: 2, text: '¿En qué año se fundó Facebook?', options: ['2004', '2006', '2002', '2008'] },
  { id: 'in11', category: 'internet', difficulty: 3, text: 'La palabra "spam" viene de ____', options: ['Una marca de carne enlatada', 'Un error de red', 'Un virus de los 90', 'Un tipo de cable'] },
  { id: 'in12', category: 'internet', difficulty: 3, text: '¿Cómo se llamaba la perra del meme "Doge"?', options: ['Kabosu', 'Cheems', 'Shiba', 'Balto'] },
  { id: 'in13', category: 'internet', difficulty: 2, text: '¿Qué es un "rickroll"?', options: ['Que te manden a un video de Rick Astley', 'Un tipo de virus', 'Un meme de gatos', 'Una estafa por correo'] },
  { id: 'in14', category: 'internet', difficulty: 2, text: '¿Qué empresa compró YouTube en 2006?', options: ['Google', 'Microsoft', 'Yahoo', 'Apple'] },
  { id: 'in15', category: 'internet', difficulty: 1, text: '¿Qué red social organiza sus comunidades en "subreddits"?', options: ['Reddit', 'Discord', 'Tumblr', '4chan'] },
  { id: 'in16', category: 'internet', difficulty: 2, text: '¿Qué significa "FOMO"?', options: ['Fear Of Missing Out', 'Fun Of My Own', 'Friends On My Own', 'Full Of Money'] },
  { id: 'in17', category: 'internet', difficulty: 2, text: '¿Cuál es el emoji más usado del mundo?', options: ['😂', '❤️', '👍', '😊'] },
  { id: 'in18', category: 'internet', difficulty: 1, text: '¿En qué plataforma se transmiten partidas de videojuegos en vivo?', options: ['Twitch', 'Vimeo', 'Dailymotion', 'Spotify'] },
  { id: 'in19', category: 'internet', difficulty: 1, text: '¿Qué significa "WWW"?', options: ['World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide'] },
  { id: 'in20', category: 'internet', difficulty: 2, text: '¿Qué app de mensajería compró Facebook en 2014?', options: ['WhatsApp', 'Telegram', 'Signal', 'Line'] },
  { id: 'in21', category: 'internet', difficulty: 3, text: 'En un foro, ¿qué quiere decir "OP"?', options: ['Original Poster', 'Over Powered', 'Open Post', 'Online Player'] },
  { id: 'in22', category: 'internet', difficulty: 1, text: '¿Cómo se llama el navegador de Google?', options: ['Chrome', 'Edge', 'Safari', 'Opera'] },
  { id: 'in23', category: 'internet', difficulty: 2, text: '¿Qué indica el candado en la barra del navegador?', options: ['Que la conexión está cifrada', 'Que el sitio no tiene virus', 'Que hace falta contraseña', 'Que el sitio es oficial'] },
  { id: 'in24', category: 'internet', difficulty: 3, text: '¿Cómo se llama el meme del chico que mira a otra chica caminando con su novia?', options: ['Distracted Boyfriend', 'Drakeposting', 'Woman Yelling at a Cat', 'Two Buttons'] },
  { id: 'in25', category: 'internet', difficulty: 2, text: '¿Qué quiere decir "streaming"?', options: ['Reproducir contenido sin descargarlo', 'Descargar más rápido', 'Grabar en vivo', 'Comprimir un video'] },
  { id: 'in26', category: 'internet', difficulty: 2, text: '¿En qué año se lanzó el primer iPhone?', options: ['2007', '2005', '2009', '2010'] },
  { id: 'in27', category: 'internet', difficulty: 1, text: '¿Qué es un hashtag?', options: ['Una etiqueta que empieza con #', 'Un usuario destacado', 'Un enlace acortado', 'Un tipo de emoji'] },
  { id: 'in28', category: 'internet', difficulty: 2, text: '¿Qué significa "IRL"?', options: ['In Real Life', 'I Really Like', 'In Real Location', 'Internet Real Life'] },
  { id: 'in29', category: 'internet', difficulty: 1, text: '¿Qué empresa creó ChatGPT?', options: ['OpenAI', 'Google', 'Meta', 'Microsoft'] },
  { id: 'in30', category: 'internet', difficulty: 1, text: '¿Qué es Discord?', options: ['Una app de chat organizada en servidores', 'Un videojuego', 'Un antivirus', 'Una red social de fotos'] },
  { id: 'in31', category: 'internet', difficulty: 1, text: '¿Qué quiere decir que algo da "cringe"?', options: ['Vergüenza ajena', 'Enojo', 'Sorpresa', 'Aburrimiento'] },
  { id: 'in32', category: 'internet', difficulty: 2, text: 'En videojuegos, ¿qué es "nerfear"?', options: ['Debilitar algo que estaba muy fuerte', 'Mejorar un personaje', 'Arreglar un error', 'Agregar contenido nuevo'] },
  { id: 'in33', category: 'internet', difficulty: 2, text: '¿En qué año se lanzó Instagram?', options: ['2010', '2008', '2012', '2014'] },
  { id: 'in34', category: 'internet', difficulty: 3, text: '¿Qué significa que un contenido sea "open source"?', options: ['Que su código es público', 'Que es gratis', 'Que no tiene autor', 'Que se puede vender'] },
  { id: 'in35', category: 'internet', difficulty: 3, text: '¿Cómo se llama la enciclopedia libre que editan voluntarios?', options: ['Wikipedia', 'Britannica', 'Wikidata', 'Wikihow'] },
];
