import type { QuipPrompt } from './types';

/**
 * Consignas para Superlativos. Acá no hay respuesta correcta: el banco solo
 * tiene que dar pie. Una consigna buena es corta, concreta y deja lugar para
 * una sola idea graciosa; si necesita explicación, no sirve.
 *
 * `{jugador}` se reemplaza por alguien de la mesa al azar. Solo lo usa el tono
 * `personal`, y el elegido también responde: es parte de la gracia.
 */
export const QUIP_PROMPTS: QuipPrompt[] = [
  // -- clásico --------------------------------------------------------------
  { id: 'qc1', tone: 'clasico', text: 'El peor nombre posible para un gato' },
  { id: 'qc2', tone: 'clasico', text: 'Lo peor que podés encontrar en la heladera de un amigo' },
  { id: 'qc3', tone: 'clasico', text: 'Una excusa pésima para faltar al trabajo' },
  { id: 'qc4', tone: 'clasico', text: 'El regalo de cumpleaños más decepcionante' },
  { id: 'qc5', tone: 'clasico', text: 'Un mal nombre para un restaurante' },
  { id: 'qc6', tone: 'clasico', text: 'La peor frase para arrancar una primera cita' },
  { id: 'qc7', tone: 'clasico', text: 'Lo último que querés escuchar del piloto del avión' },
  { id: 'qc8', tone: 'clasico', text: 'Un superpoder completamente inútil' },
  { id: 'qc9', tone: 'clasico', text: 'El peor consejo para alguien que se va a casar' },
  { id: 'qc10', tone: 'clasico', text: 'Una materia que deberían dar en la escuela y no dan' },
  { id: 'qc11', tone: 'clasico', text: 'Lo peor que puede decir un médico mientras te revisa' },
  { id: 'qc12', tone: 'clasico', text: 'Un mal eslogan para una funeraria' },
  { id: 'qc13', tone: 'clasico', text: 'El peor premio que te puede tocar en una rifa' },
  { id: 'qc14', tone: 'clasico', text: 'Algo que nunca dirías en un ascensor lleno' },
  { id: 'qc15', tone: 'clasico', text: 'La peor manera de terminar un audio de WhatsApp' },
  { id: 'qc16', tone: 'clasico', text: 'Un mal nombre para un perro guardián' },
  { id: 'qc17', tone: 'clasico', text: 'Lo peor que podés encontrar en el bolsillo de una campera vieja' },
  { id: 'qc18', tone: 'clasico', text: 'Una razón ridícula para llamar a la policía' },
  { id: 'qc19', tone: 'clasico', text: 'El peor sabor de helado que se podría inventar' },
  { id: 'qc20', tone: 'clasico', text: 'Algo que un superhéroe jamás debería decir' },
  { id: 'qc21', tone: 'clasico', text: 'Un mal nombre para un huracán' },
  { id: 'qc22', tone: 'clasico', text: 'La peor pizza del mundo lleva…' },
  { id: 'qc23', tone: 'clasico', text: 'Lo peor que puede pasar en un asado' },
  { id: 'qc24', tone: 'clasico', text: 'Una excusa mala para llegar tarde a un casamiento' },
  { id: 'qc25', tone: 'clasico', text: 'El peor tatuaje posible' },
  { id: 'qc26', tone: 'clasico', text: 'Un mal nombre para una banda de rock' },
  { id: 'qc27', tone: 'clasico', text: 'Algo que no querés ver en la cocina de un restaurante' },
  { id: 'qc28', tone: 'clasico', text: 'El peor uso posible para una máquina del tiempo' },
  { id: 'qc29', tone: 'clasico', text: 'Lo peor que te puede decir un taxista' },
  { id: 'qc30', tone: 'clasico', text: 'Un mal nombre para un cereal de desayuno' },
  { id: 'qc31', tone: 'clasico', text: 'La peor manera de despertar a alguien' },
  { id: 'qc32', tone: 'clasico', text: 'Algo que arruina una película en los primeros cinco minutos' },
  { id: 'qc33', tone: 'clasico', text: 'El peor regalo para un amigo invisible' },
  { id: 'qc34', tone: 'clasico', text: 'Lo peor que podés gritar en una biblioteca' },
  { id: 'qc35', tone: 'clasico', text: 'Una habilidad inútil para poner en el currículum' },
  { id: 'qc36', tone: 'clasico', text: 'Un mal nombre para un barco' },
  { id: 'qc37', tone: 'clasico', text: 'La peor cosa para llevar a un picnic' },
  { id: 'qc38', tone: 'clasico', text: 'Algo que jamás pondrías en una torta de cumpleaños' },
  { id: 'qc39', tone: 'clasico', text: 'El deporte olímpico más innecesario que se podría inventar' },
  { id: 'qc40', tone: 'clasico', text: 'Lo peor que puede tener un hotel cinco estrellas' },
  { id: 'qc41', tone: 'clasico', text: 'Una mala razón para renunciar a un trabajo' },
  { id: 'qc42', tone: 'clasico', text: 'El peor souvenir para traer de un viaje' },
  { id: 'qc43', tone: 'clasico', text: 'Algo que no debería venderse en una máquina expendedora' },
  { id: 'qc44', tone: 'clasico', text: 'La peor frase para tener bordada en un almohadón' },
  { id: 'qc45', tone: 'clasico', text: 'Un mal nombre para un perfume' },
  { id: 'qc46', tone: 'clasico', text: 'Lo peor que puede pasar en un ascensor trabado' },

  // -- nerd -----------------------------------------------------------------
  { id: 'qn1', tone: 'nerd', text: 'Un mal nombre para una variable' },
  { id: 'qn2', tone: 'nerd', text: 'El peor mensaje de error posible' },
  { id: 'qn3', tone: 'nerd', text: 'Una feature que nadie pidió' },
  { id: 'qn4', tone: 'nerd', text: 'Un mal nombre para un lenguaje de programación' },
  { id: 'qn5', tone: 'nerd', text: 'Lo peor que puede decir tu jefe en una reunión' },
  { id: 'qn6', tone: 'nerd', text: 'Un mal nombre para un jefe final' },
  { id: 'qn7', tone: 'nerd', text: 'El poder más inútil para un personaje de anime' },
  { id: 'qn8', tone: 'nerd', text: 'Una razón absurda por la que se cayó producción' },
  { id: 'qn9', tone: 'nerd', text: 'El peor final posible para El Señor de los Anillos' },
  { id: 'qn10', tone: 'nerd', text: 'Un mal nombre para una nave espacial' },
  { id: 'qn11', tone: 'nerd', text: 'La peor mecánica que podría tener un videojuego' },
  { id: 'qn12', tone: 'nerd', text: 'Algo que Batman jamás diría' },
  { id: 'qn13', tone: 'nerd', text: 'Un plan de villano condenado al fracaso' },
  { id: 'qn14', tone: 'nerd', text: 'Un mal nombre para un framework de JavaScript' },
  { id: 'qn15', tone: 'nerd', text: 'Lo peor que te pueden comentar en un code review' },
  { id: 'qn16', tone: 'nerd', text: 'Una secuela innecesaria de una película perfecta' },
  { id: 'qn17', tone: 'nerd', text: 'El peor comentario que podés dejar en el código' },
  { id: 'qn18', tone: 'nerd', text: 'Un mal nombre para un planeta recién descubierto' },
  { id: 'qn19', tone: 'nerd', text: 'Lo peor que podés encontrar en un proyecto viejo' },
  { id: 'qn20', tone: 'nerd', text: 'Una excusa mala para no escribir tests' },
  { id: 'qn21', tone: 'nerd', text: 'El peor contenido descargable para un juego' },
  { id: 'qn22', tone: 'nerd', text: 'Un mal nombre para un Pokémon' },
  { id: 'qn23', tone: 'nerd', text: 'La forma más patética de morir en un videojuego' },
  { id: 'qn24', tone: 'nerd', text: 'Algo que arruinaría Star Wars para siempre' },
  { id: 'qn25', tone: 'nerd', text: 'El peor consejo de programación' },
  { id: 'qn26', tone: 'nerd', text: 'Un mal nombre para un algoritmo' },
  { id: 'qn27', tone: 'nerd', text: 'Lo peor que puede pasarte en una partida online' },
  { id: 'qn28', tone: 'nerd', text: 'Una mala razón para pisar la rama principal' },
  { id: 'qn29', tone: 'nerd', text: 'El personaje jugable más innecesario' },
  { id: 'qn30', tone: 'nerd', text: 'Un mal nombre para una inteligencia artificial' },
  { id: 'qn31', tone: 'nerd', text: 'La frase más molesta que puede repetir un personaje' },
  { id: 'qn32', tone: 'nerd', text: 'Una idea pésima para un remake' },
  { id: 'qn33', tone: 'nerd', text: 'El logro más humillante que podría dar un juego' },
  { id: 'qn34', tone: 'nerd', text: 'Un mal nombre para un servidor de producción' },
  { id: 'qn35', tone: 'nerd', text: 'Lo peor que puede tener una casa inteligente' },
  { id: 'qn36', tone: 'nerd', text: 'Una regla de rol imposible de jugar' },
  { id: 'qn37', tone: 'nerd', text: 'El peor superpoder para pelear contra un dragón' },
  { id: 'qn38', tone: 'nerd', text: 'Un mal nombre para una espada legendaria' },

  // -- personal (usan {jugador}) --------------------------------------------
  { id: 'qp1', tone: 'personal', text: 'Lo peor que podría tener {jugador} en el historial' },
  { id: 'qp2', tone: 'personal', text: 'El apodo que {jugador} se merece de verdad' },
  { id: 'qp3', tone: 'personal', text: 'Una excusa muy de {jugador} para no venir a comer' },
  { id: 'qp4', tone: 'personal', text: 'Lo primero que haría {jugador} si se ganara la lotería' },
  { id: 'qp5', tone: 'personal', text: 'Algo que {jugador} nunca admitiría en voz alta' },
  { id: 'qp6', tone: 'personal', text: 'El título de la autobiografía de {jugador}' },
  { id: 'qp7', tone: 'personal', text: 'Lo que grita {jugador} cuando pierde' },
  { id: 'qp8', tone: 'personal', text: 'La peor decisión que tomó {jugador} este año' },
  { id: 'qp9', tone: 'personal', text: 'Lo que hay en la mochila de {jugador} ahora mismo' },
  { id: 'qp10', tone: 'personal', text: 'La contraseña de {jugador}, seguro' },
  { id: 'qp11', tone: 'personal', text: 'Lo que le falta a {jugador} para ser feliz' },
  { id: 'qp12', tone: 'personal', text: 'Un consejo malísimo que daría {jugador}' },
  { id: 'qp13', tone: 'personal', text: 'Lo que googlea {jugador} a las tres de la mañana' },
  { id: 'qp14', tone: 'personal', text: 'El superpoder que le tocaría a {jugador}' },
  { id: 'qp15', tone: 'personal', text: 'Lo que va a decir {jugador} en un discurso de casamiento' },
  { id: 'qp16', tone: 'personal', text: 'Una razón muy de {jugador} para llegar tarde' },
  { id: 'qp17', tone: 'personal', text: 'Lo que pediría {jugador} como última cena' },
  { id: 'qp18', tone: 'personal', text: 'El trabajo perfecto para {jugador}' },
  { id: 'qp19', tone: 'personal', text: 'Algo que {jugador} tiene guardado y no debería' },
  { id: 'qp20', tone: 'personal', text: 'La forma más rápida de hacer enojar a {jugador}' },
  { id: 'qp21', tone: 'personal', text: 'Lo que {jugador} le diría a un extraterrestre' },
  { id: 'qp22', tone: 'personal', text: 'Lo que hace {jugador} cuando nadie lo mira' },
  { id: 'qp23', tone: 'personal', text: 'El peor plan de fin de semana de {jugador}' },
  { id: 'qp24', tone: 'personal', text: 'Lo que va a estar haciendo {jugador} en diez años' },
  { id: 'qp25', tone: 'personal', text: 'La materia en la que {jugador} sería profesor' },
  { id: 'qp26', tone: 'personal', text: 'Algo que {jugador} nunca va a superar' },
  { id: 'qp27', tone: 'personal', text: 'El animal que sería {jugador}' },
  { id: 'qp28', tone: 'personal', text: 'Lo que dice {jugador} apenas se despierta' },
  { id: 'qp29', tone: 'personal', text: 'Lo que {jugador} pediría si le dieran un solo deseo' },
  { id: 'qp30', tone: 'personal', text: 'El mejor regalo posible para {jugador}' },
  { id: 'qp31', tone: 'personal', text: 'La app que {jugador} usa más de lo que admite' },
  { id: 'qp32', tone: 'personal', text: 'Lo que arruinaría el día de {jugador} en un segundo' },
  { id: 'qp33', tone: 'personal', text: 'El disfraz perfecto para {jugador}' },
  { id: 'qp34', tone: 'personal', text: 'Lo que {jugador} salvaría de un incendio' },
];
