import type { PollPrompt } from './types';

/**
 * Consignas para Encuesta. La regla al sumar es al revés que en trivia: una
 * consigna buena es la que tiene una respuesta **obvia pero no única**. Si todos
 * van a escribir lo mismo seguro, no hay juego; si el universo es infinito,
 * tampoco. El punto dulce es "nombrá un animal de granja": hay una favorita
 * clara, pero siempre aparece el que pone cabra.
 */
export const POLL_PROMPTS: PollPrompt[] = [
  { id: 'e1', text: 'Nombrá un animal de granja' },
  { id: 'e2', text: 'Un color' },
  { id: 'e3', text: 'Una fruta' },
  { id: 'e4', text: 'Una marca de gaseosa' },
  { id: 'e5', text: 'Algo que hay en toda cocina' },
  { id: 'e6', text: 'Un superhéroe' },
  { id: 'e7', text: 'Un día de la semana' },
  { id: 'e8', text: 'Un animal del zoológico' },
  { id: 'e9', text: 'Una parte del cuerpo' },
  { id: 'e10', text: 'Un instrumento musical' },
  { id: 'e11', text: 'Algo que se guarda en la heladera' },
  { id: 'e12', text: 'Un país de Europa' },
  { id: 'e13', text: 'Una verdura' },
  { id: 'e14', text: 'Un medio de transporte' },
  { id: 'e15', text: 'Algo que hay en una plaza' },
  { id: 'e16', text: 'Una profesión' },
  { id: 'e17', text: 'Un deporte' },
  { id: 'e18', text: 'Algo que llevás siempre encima' },
  { id: 'e19', text: 'Un mes del año' },
  { id: 'e20', text: 'Una película de Disney' },
  { id: 'e21', text: 'Algo que se rompe fácil' },
  { id: 'e22', text: 'Una bebida caliente' },
  { id: 'e23', text: 'Algo que hay en un baño' },
  { id: 'e24', text: 'Un número del 1 al 10' },
  { id: 'e25', text: 'Una red social' },
  { id: 'e26', text: 'Algo que se come con la mano' },
  { id: 'e27', text: 'Un gusto de pizza' },
  { id: 'e28', text: 'Un planeta' },
  { id: 'e29', text: 'Algo que hace ruido a la mañana' },
  { id: 'e30', text: 'Una marca de zapatillas' },
  { id: 'e31', text: 'Un animal peligroso' },
  { id: 'e32', text: 'Algo que hay en un auto' },
  { id: 'e33', text: 'Un postre' },
  { id: 'e34', text: 'Una estación del año' },
  { id: 'e35', text: 'Algo que junta polvo en tu casa' },
  { id: 'e36', text: 'Un electrodoméstico' },
  { id: 'e37', text: 'Un felino' },
  { id: 'e38', text: 'Algo que te olvidás siempre' },
  { id: 'e39', text: 'Una herramienta' },
  { id: 'e40', text: 'Un juego de mesa' },
  { id: 'e41', text: 'Algo que hay en una oficina' },
  { id: 'e42', text: 'Un condimento' },
  { id: 'e43', text: 'Una carrera universitaria' },
  { id: 'e44', text: 'Algo que se hace los domingos' },
  { id: 'e45', text: 'Un animal que vuela' },
  { id: 'e46', text: 'Una parte de la casa' },
  { id: 'e47', text: 'Algo que se compra en un kiosco' },
  { id: 'e48', text: 'Un mueble' },
  { id: 'e49', text: 'Una banda de rock' },
  { id: 'e50', text: 'Algo que se le pone a un sándwich' },
  { id: 'e51', text: 'Un idioma' },
  { id: 'e52', text: 'Algo amarillo' },
  { id: 'e53', text: 'Algo que hay en una mochila' },
  { id: 'e54', text: 'Una prenda de ropa' },
  { id: 'e55', text: 'Un tipo de queso' },
  { id: 'e56', text: 'Algo que hace un gato' },
  { id: 'e57', text: 'Un juego de la infancia' },
  { id: 'e58', text: 'Algo que corte' },
  { id: 'e59', text: 'Algo que se pide de delivery a la madrugada' },
  { id: 'e60', text: 'Un tipo de calzado' },
  { id: 'e61', text: 'Una ciudad de Argentina' },
  { id: 'e62', text: 'Algo que hay en un hospital' },
  { id: 'e63', text: 'Una excusa para no ir a un cumpleaños' },
  { id: 'e64', text: 'Un dinosaurio' },
  { id: 'e65', text: 'Algo que da miedo' },
  { id: 'e66', text: 'Un tipo de pasta' },
  { id: 'e67', text: 'Una emoción' },
  { id: 'e68', text: 'Algo que se lleva a la playa' },
  { id: 'e69', text: 'Un personaje de dibujos animados' },
  { id: 'e70', text: 'Algo redondo' },
  { id: 'e71', text: 'Algo que nunca falta en un supermercado' },
  { id: 'e72', text: 'Un tipo de pan' },
  { id: 'e73', text: 'Un animal marino' },
  { id: 'e74', text: 'Algo que se hace cuando llueve' },
  { id: 'e75', text: 'Una marca de celular' },
  { id: 'e76', text: 'Algo pegajoso' },
  { id: 'e77', text: 'Algo que hay debajo de una cama' },
  { id: 'e78', text: 'Un insecto' },
  { id: 'e79', text: 'Un sabor de helado' },
  { id: 'e80', text: 'Algo que huele feo' },
  { id: 'e81', text: 'Algo que hay en una billetera' },
  { id: 'e82', text: 'Una figura geométrica' },
  { id: 'e83', text: 'Algo que se hace en el gimnasio' },
  { id: 'e84', text: 'Un animal doméstico' },
  { id: 'e85', text: 'Algo que hay en un cumpleaños de nenes' },
  { id: 'e86', text: 'Algo que se usa para escribir' },
  { id: 'e87', text: 'Algo que brilla' },
  { id: 'e88', text: 'Algo que se ve en el cielo' },
  { id: 'e89', text: 'Una bebida con alcohol' },
  { id: 'e90', text: 'Algo que se derrite' },
  { id: 'e91', text: 'Algo que se hace antes de dormir' },
  { id: 'e92', text: 'Un tipo de árbol' },
  { id: 'e93', text: 'Lo primero que hacés al llegar a casa' },
  { id: 'e94', text: 'Una app que tienen todos en el celular' },
  { id: 'e95', text: 'Algo que se dice en un asado' },
  { id: 'e96', text: 'Un animal que se pueda tener en un departamento' },
  { id: 'e97', text: 'Algo que siempre se pierde en la casa' },
  { id: 'e98', text: 'Un villano de película' },
  { id: 'e99', text: 'Algo que hay en un escritorio' },
  { id: 'e100', text: 'Una golosina' },
  { id: 'e101', text: 'Algo que hace ruido de noche' },
  { id: 'e102', text: 'Un animal con rayas' },
  { id: 'e103', text: 'Algo que se regala para un cumpleaños' },
  { id: 'e104', text: 'Una comida que se come fría' },
  { id: 'e105', text: 'Algo que hay en un ascensor' },
  { id: 'e106', text: 'Un objeto que tiene botones' },
  { id: 'e107', text: 'Algo que se hace en la ducha' },
  { id: 'e108', text: 'Un animal que duerme mucho' },
];
